# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/commands.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fleet/v1/commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66leet/v1/commands.proto\x12\x08\x66leet.v1\"-\n\tPkgUpdate\x12\x0f\n\x07\x63lasses\x18\x01 \x03(\t\x12\x0f\n\x07\x64ry_run\x18\x02 \x01(\x08\"/\n\x06Reboot\x12\x15\n\rdelay_seconds\x18\x01 \x01(\r\x12\x0e\n\x06reason\x18\x02 \x01(\t\"C\n\tShellExec\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x17\n\x0ftimeout_seconds\x18\x03 \x01(\r\">\n\x0cTerminalOpen\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04rows\x18\x03 \x01(\r\"\x81\x01\n\x0c\x46ileTransfer\x12\'\n\x03\x64ir\x18\x01 \x01(\x0e\x32\x1a.fleet.v1.FileTransfer.Dir\x12\x13\n\x0bremote_path\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\"\x1f\n\x03\x44ir\x12\n\n\x06UPLOAD\x10\x00\x12\x0c\n\x08\x44OWNLOAD\x10\x01\")\n\x08\x44ockerOp\x12\n\n\x02op\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\"\x18\n\x08GetFacts\x12\x0c\n\x04keys\x18\x01 \x03(\t\"2\n\x0cPluginInvoke\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x42-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet.v1.commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/hlhelper/hl-agent/proto/fleet/v1'
  _globals['_PKGUPDATE']._serialized_start=37
  _globals['_PKGUPDATE']._serialized_end=82
  _globals['_REBOOT']._serialized_start=84
  _globals['_REBOOT']._serialized_end=131
  _globals['_SHELLEXEC']._serialized_start=133
  _globals['_SHELLEXEC']._serialized_end=200
  _globals['_TERMINALOPEN']._serialized_start=202
  _globals['_TERMINALOPEN']._serialized_end=264
  _globals['_FILETRANSFER']._serialized_start=267
  _globals['_FILETRANSFER']._serialized_end=396
  _globals['_FILETRANSFER_DIR']._serialized_start=365
  _globals['_FILETRANSFER_DIR']._serialized_end=396
  _globals['_DOCKEROP']._serialized_start=398
  _globals['_DOCKEROP']._serialized_end=439
  _globals['_GETFACTS']._serialized_start=441
  _globals['_GETFACTS']._serialized_end=465
  _globals['_PLUGININVOKE']._serialized_start=467
  _globals['_PLUGININVOKE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
