# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fleet/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from fleet.v1 import commands_pb2 as fleet_dot_v1_dot_commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66leet/v1/envelope.proto\x12\x08\x66leet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17\x66leet/v1/commands.proto\";\n\x0f\x43\x61pabilityToken\x12\x0f\n\x07\x62iscuit\x18\x01 \x01(\x0c\x12\x17\n\x0f\x64\x65\x63lared_scopes\x18\x02 \x03(\t\"\x99\x05\n\x0f\x43ommandEnvelope\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07host_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\r\n\x05nonce\x18\x04 \x01(\x0c\x12-\n\tissued_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tissued_by\x18\x07 \x01(\t\x12!\n\x04risk\x18\x08 \x01(\x0e\x32\x13.fleet.v1.RiskLevel\x12-\n\ncapability\x18\t \x01(\x0b\x32\x19.fleet.v1.CapabilityToken\x12)\n\npkg_update\x18\x64 \x01(\x0b\x32\x13.fleet.v1.PkgUpdateH\x00\x12\"\n\x06reboot\x18\x65 \x01(\x0b\x32\x10.fleet.v1.RebootH\x00\x12)\n\nshell_exec\x18\x66 \x01(\x0b\x32\x13.fleet.v1.ShellExecH\x00\x12/\n\rterminal_open\x18g \x01(\x0b\x32\x16.fleet.v1.TerminalOpenH\x00\x12/\n\rfile_transfer\x18h \x01(\x0b\x32\x16.fleet.v1.FileTransferH\x00\x12\'\n\tdocker_op\x18i \x01(\x0b\x32\x12.fleet.v1.DockerOpH\x00\x12\'\n\tget_facts\x18j \x01(\x0b\x32\x12.fleet.v1.GetFactsH\x00\x12/\n\rplugin_invoke\x18k \x01(\x0b\x32\x16.fleet.v1.PluginInvokeH\x00\x12\x12\n\tsignature\x18\xc8\x01 \x01(\x0c\x42\t\n\x07payload*6\n\tRiskLevel\x12\x0c\n\x08RISK_LOW\x10\x00\x12\x0c\n\x08RISK_MED\x10\x01\x12\r\n\tRISK_HIGH\x10\x02\x42-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/hlhelper/hl-agent/proto/fleet/v1'
  _globals['_RISKLEVEL']._serialized_start=824
  _globals['_RISKLEVEL']._serialized_end=878
  _globals['_CAPABILITYTOKEN']._serialized_start=95
  _globals['_CAPABILITYTOKEN']._serialized_end=154
  _globals['_COMMANDENVELOPE']._serialized_start=157
  _globals['_COMMANDENVELOPE']._serialized_end=822
# @@protoc_insertion_point(module_scope)
