# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fleet/v1/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66leet/v1/inventory.proto\x12\x08\x66leet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n\x10PackageInventory\x12\x0f\n\x07host_id\x18\x01 \x01(\t\x12&\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x05\x61\x64\x64\x65\x64\x18\x03 \x03(\x0b\x32\x1e.fleet.v1.PackageInventory.Pkg\x12/\n\x07removed\x18\x04 \x03(\x0b\x32\x1e.fleet.v1.PackageInventory.Pkg\x12\x15\n\rfull_snapshot\x18\x05 \x01(\x08\x1aU\n\x03Pkg\x12\x11\n\tecosystem\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0c\n\x04\x61rch\x18\x05 \x01(\t\"\x8f\x02\n\x12\x43ontainerInventory\x12\x0f\n\x07host_id\x18\x01 \x01(\t\x12&\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\ncontainers\x18\x03 \x03(\x0b\x32&.fleet.v1.ContainerInventory.Container\x12\x15\n\rfull_snapshot\x18\x04 \x01(\x08\x1am\n\tContainer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\timage_ref\x18\x03 \x01(\t\x12\x14\n\x0cimage_digest\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x06 \x01(\t\"\xf2\x02\n\tHostFacts\x12\x0f\n\x07host_id\x18\x01 \x01(\t\x12&\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x04sshd\x18\x03 \x03(\x0b\x32\x1d.fleet.v1.HostFacts.SshdEntry\x12/\n\x06sysctl\x18\x04 \x03(\x0b\x32\x1f.fleet.v1.HostFacts.SysctlEntry\x12\x0e\n\x06mounts\x18\x05 \x03(\t\x12\x32\n\x08\x66s_perms\x18\x06 \x03(\x0b\x32 .fleet.v1.HostFacts.FsPermsEntry\x1a+\n\tSshdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bSysctlEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0c\x46sPermsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet.v1.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/hlhelper/hl-agent/proto/fleet/v1'
  _globals['_HOSTFACTS_SSHDENTRY']._loaded_options = None
  _globals['_HOSTFACTS_SSHDENTRY']._serialized_options = b'8\001'
  _globals['_HOSTFACTS_SYSCTLENTRY']._loaded_options = None
  _globals['_HOSTFACTS_SYSCTLENTRY']._serialized_options = b'8\001'
  _globals['_HOSTFACTS_FSPERMSENTRY']._loaded_options = None
  _globals['_HOSTFACTS_FSPERMSENTRY']._serialized_options = b'8\001'
  _globals['_PACKAGEINVENTORY']._serialized_start=72
  _globals['_PACKAGEINVENTORY']._serialized_end=353
  _globals['_PACKAGEINVENTORY_PKG']._serialized_start=268
  _globals['_PACKAGEINVENTORY_PKG']._serialized_end=353
  _globals['_CONTAINERINVENTORY']._serialized_start=356
  _globals['_CONTAINERINVENTORY']._serialized_end=627
  _globals['_CONTAINERINVENTORY_CONTAINER']._serialized_start=518
  _globals['_CONTAINERINVENTORY_CONTAINER']._serialized_end=627
  _globals['_HOSTFACTS']._serialized_start=630
  _globals['_HOSTFACTS']._serialized_end=1000
  _globals['_HOSTFACTS_SSHDENTRY']._serialized_start=862
  _globals['_HOSTFACTS_SSHDENTRY']._serialized_end=905
  _globals['_HOSTFACTS_SYSCTLENTRY']._serialized_start=907
  _globals['_HOSTFACTS_SYSCTLENTRY']._serialized_end=952
  _globals['_HOSTFACTS_FSPERMSENTRY']._serialized_start=954
  _globals['_HOSTFACTS_FSPERMSENTRY']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
