# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fleet.v1 import agent_bridge_pb2 as fleet_dot_v1_dot_agent__bridge__pb2
from fleet.v1 import reenroll_pb2 as fleet_dot_v1_dot_reenroll__pb2


class ReEnrollStub(object):
    """ReEnroll is dialed TLS-only (no client cert). Auth is via Ed25519 challenge
    signed with the host's durable signing key.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Challenge = channel.unary_unary(
                '/fleet.v1.ReEnroll/Challenge',
                request_serializer=fleet_dot_v1_dot_reenroll__pb2.ChallengeRequest.SerializeToString,
                response_deserializer=fleet_dot_v1_dot_reenroll__pb2.ChallengeResponse.FromString,
                )
        self.Complete = channel.unary_unary(
                '/fleet.v1.ReEnroll/Complete',
                request_serializer=fleet_dot_v1_dot_reenroll__pb2.CompleteRequest.SerializeToString,
                response_deserializer=fleet_dot_v1_dot_agent__bridge__pb2.CertIssueResponse.FromString,
                )


class ReEnrollServicer(object):
    """ReEnroll is dialed TLS-only (no client cert). Auth is via Ed25519 challenge
    signed with the host's durable signing key.
    """

    def Challenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReEnrollServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Challenge': grpc.unary_unary_rpc_method_handler(
                    servicer.Challenge,
                    request_deserializer=fleet_dot_v1_dot_reenroll__pb2.ChallengeRequest.FromString,
                    response_serializer=fleet_dot_v1_dot_reenroll__pb2.ChallengeResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=fleet_dot_v1_dot_reenroll__pb2.CompleteRequest.FromString,
                    response_serializer=fleet_dot_v1_dot_agent__bridge__pb2.CertIssueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.v1.ReEnroll', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReEnroll(object):
    """ReEnroll is dialed TLS-only (no client cert). Auth is via Ed25519 challenge
    signed with the host's durable signing key.
    """

    @staticmethod
    def Challenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fleet.v1.ReEnroll/Challenge',
            fleet_dot_v1_dot_reenroll__pb2.ChallengeRequest.SerializeToString,
            fleet_dot_v1_dot_reenroll__pb2.ChallengeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fleet.v1.ReEnroll/Complete',
            fleet_dot_v1_dot_reenroll__pb2.CompleteRequest.SerializeToString,
            fleet_dot_v1_dot_agent__bridge__pb2.CertIssueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
