# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet/v1/reenroll.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'fleet/v1/reenroll.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from fleet.v1 import agent_bridge_pb2 as fleet_dot_v1_dot_agent__bridge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66leet/v1/reenroll.proto\x12\x08\x66leet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x66leet/v1/agent_bridge.proto\"R\n\x10\x43hallengeRequest\x12\x17\n\x07host_id\x18\x01 \x01(\tR\x06hostId\x12%\n\x0esigning_pubkey\x18\x02 \x01(\x0cR\rsigningPubkey\"d\n\x11\x43hallengeResponse\x12\x14\n\x05nonce\x18\x01 \x01(\x0cR\x05nonce\x12\x39\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\texpiresAt\"\xa3\x01\n\x0f\x43ompleteRequest\x12\x17\n\x07host_id\x18\x01 \x01(\tR\x06hostId\x12\x14\n\x05nonce\x18\x02 \x01(\x0cR\x05nonce\x12\x1c\n\tsignature\x18\x03 \x01(\x0cR\tsignature\x12\x17\n\x07\x63sr_pem\x18\x04 \x01(\x0cR\x06\x63srPem\x12*\n\x02ts\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02ts2\x94\x01\n\x08ReEnroll\x12\x44\n\tChallenge\x12\x1a.fleet.v1.ChallengeRequest\x1a\x1b.fleet.v1.ChallengeResponse\x12\x42\n\x08\x43omplete\x12\x19.fleet.v1.CompleteRequest\x1a\x1b.fleet.v1.CertIssueResponseB-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet.v1.reenroll_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/hlhelper/hl-agent/proto/fleet/v1'
  _globals['_CHALLENGEREQUEST']._serialized_start=99
  _globals['_CHALLENGEREQUEST']._serialized_end=181
  _globals['_CHALLENGERESPONSE']._serialized_start=183
  _globals['_CHALLENGERESPONSE']._serialized_end=283
  _globals['_COMPLETEREQUEST']._serialized_start=286
  _globals['_COMPLETEREQUEST']._serialized_end=449
  _globals['_REENROLL']._serialized_start=452
  _globals['_REENROLL']._serialized_end=600
# @@protoc_insertion_point(module_scope)
