// Code generated by task; DO NOT EDIT.
//go:build darwin

package service

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLaunchdManagerRender(t *testing.T) {
	u := Unit{
		Name:        "test-agent",
		Description: "Test Agent Service",
		ExecPath:    "/usr/local/bin/test-agent",
		ExecArgs:    []string{"run", "--debug"},
		User:        "testuser",
	}

	content, err := renderLaunchd(u)
	if err != nil {
		t.Fatalf("renderLaunchd() error = %v", err)
	}

	checks := []string{
		"<?xml",
		"com.hlhelper.test-agent",
		"/usr/local/bin/test-agent",
		"run",
		"--debug",
		"<true/>",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("rendered template missing: %q\n\nGot:\n%s", check, content)
		}
	}
}

func TestLaunchdManagerInstall(t *testing.T) {
	unitDir := t.TempDir()
	mgr := &launchdManager{unitDir: unitDir}

	u := Unit{
		Name:        "test-service",
		Description: "Test Service",
		ExecPath:    "/bin/echo",
		ExecArgs:    []string{"hello"},
	}

	// Mock execRun to avoid actually calling launchctl
	oldExecRun := execRun
	defer func() { execRun = oldExecRun }()

	calls := []struct {
		name string
		args []string
	}{}

	execRun = func(name string, args ...string) error {
		calls = append(calls, struct {
			name string
			args []string
		}{name, args})
		return nil
	}

	// Install
	if err := mgr.Install(u); err != nil {
		t.Fatalf("Install() error = %v", err)
	}

	// Check plist was written
	plistPath := filepath.Join(unitDir, "com.hlhelper.test-service.plist")
	_, err := os.Stat(plistPath)
	if err != nil {
		t.Fatalf("plist file not found: %v", err)
	}

	// Check execRun was called with launchctl load
	if len(calls) != 1 {
		t.Errorf("expected 1 execRun call, got %d: %v", len(calls), calls)
	}
	if calls[0].name != "launchctl" || len(calls[0].args) < 2 || calls[0].args[0] != "load" {
		t.Errorf("expected launchctl load call, got: %v", calls[0])
	}
}
