// Code generated by task; DO NOT EDIT.
//go:build darwin

package service

import (
	"bytes"
	"embed"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

type launchdManager struct {
	unitDir string
}

func newLaunchd() Manager {
	return &launchdManager{
		unitDir: "/Library/LaunchDaemons",
	}
}

func (l *launchdManager) Kind() string {
	return "launchd"
}

func (l *launchdManager) Install(u Unit) error {
	content, err := renderLaunchd(u)
	if err != nil {
		return fmt.Errorf("render launchd plist: %w", err)
	}

	label := "com.hlhelper." + u.Name
	plistPath := filepath.Join(l.unitDir, label+".plist")
	if err := os.WriteFile(plistPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write plist: %w", err)
	}

	if err := execRun("launchctl", "load", "-w", plistPath); err != nil {
		return fmt.Errorf("launchctl load: %w", err)
	}

	return nil
}

func (l *launchdManager) Uninstall(name string) error {
	label := "com.hlhelper." + name
	plistPath := filepath.Join(l.unitDir, label+".plist")

	if err := execRun("launchctl", "unload", "-w", plistPath); err != nil {
		// Ignore error if already unloaded
		_ = err
	}

	if err := os.Remove(plistPath); err != nil {
		return fmt.Errorf("remove plist: %w", err)
	}

	return nil
}

func (l *launchdManager) Start(name string) error {
	label := "com.hlhelper." + name
	return execRun("launchctl", "kickstart", "-k", "system/"+label)
}

func (l *launchdManager) Stop(name string) error {
	label := "com.hlhelper." + name
	return execRun("launchctl", "stop", "system/"+label)
}

func (l *launchdManager) Restart(name string) error {
	if err := l.Stop(name); err != nil {
		// Continue anyway
		_ = err
	}
	return l.Start(name)
}

func (l *launchdManager) Status(name string) (State, error) {
	label := "com.hlhelper." + name
	cmd := exec.Command("launchctl", "list", label)
	output, err := cmd.Output()
	if err != nil {
		return StateUnknown, err
	}

	// launchctl list output for a running service includes the PID on first column
	lines := strings.Split(string(output), "\n")
	if len(lines) > 0 {
		fields := strings.Fields(lines[0])
		if len(fields) > 0 {
			pid := fields[0]
			if pid != "-" {
				return StateRunning, nil
			}
		}
	}

	return StateStopped, nil
}

func (l *launchdManager) Logs(name string, follow bool, lines int) (io.ReadCloser, error) {
	logPath := filepath.Join("/var/log", name+".log")

	if follow {
		args := []string{"-f"}
		if lines > 0 {
			args = append([]string{"-n", fmt.Sprintf("%d", lines)}, args...)
		}
		args = append(args, logPath)

		cmd := exec.Command("tail", args...)
		pipe, err := cmd.StdoutPipe()
		if err != nil {
			return nil, err
		}

		if err := cmd.Start(); err != nil {
			return nil, err
		}

		return &cmdReadCloser{cmd, pipe}, nil
	}

	file, err := os.Open(logPath)
	if err != nil {
		return nil, err
	}

	return file, nil
}

// renderLaunchd renders the launchd plist template
func renderLaunchd(u Unit) (string, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/launchd.plist.tmpl")
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, u); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// cmdReadCloser wraps an exec.Cmd and its stdout pipe
type cmdReadCloser struct {
	cmd  *exec.Cmd
	pipe io.ReadCloser
}

func (c *cmdReadCloser) Read(p []byte) (int, error) {
	return c.pipe.Read(p)
}

func (c *cmdReadCloser) Close() error {
	c.pipe.Close()
	return c.cmd.Wait()
}

// execRun is a package-level var that can be overridden in tests
var execRun = func(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	return cmd.Run()
}
