// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

type openrcManager struct {
	unitDir string
}

func newOpenRC() Manager {
	return &openrcManager{
		unitDir: "/etc/init.d",
	}
}

func (o *openrcManager) Kind() string {
	return "openrc"
}

func (o *openrcManager) Install(u Unit) error {
	content, err := renderOpenrc(u)
	if err != nil {
		return fmt.Errorf("render openrc unit: %w", err)
	}

	scriptPath := filepath.Join(o.unitDir, u.Name)
	if err := os.WriteFile(scriptPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("write init script: %w", err)
	}

	if err := execRun("rc-update", "add", u.Name, "default"); err != nil {
		return fmt.Errorf("rc-update add: %w", err)
	}

	return nil
}

func (o *openrcManager) Uninstall(name string) error {
	if err := execRun("rc-service", name, "stop"); err != nil {
		// Ignore error if already stopped
		_ = err
	}

	if err := execRun("rc-update", "del", name, "default"); err != nil {
		return fmt.Errorf("rc-update del: %w", err)
	}

	scriptPath := filepath.Join(o.unitDir, name)
	if err := os.Remove(scriptPath); err != nil {
		return fmt.Errorf("remove init script: %w", err)
	}

	return nil
}

func (o *openrcManager) Start(name string) error {
	return execRun("rc-service", name, "start")
}

func (o *openrcManager) Stop(name string) error {
	return execRun("rc-service", name, "stop")
}

func (o *openrcManager) Restart(name string) error {
	return execRun("rc-service", name, "restart")
}

func (o *openrcManager) Status(name string) (State, error) {
	cmd := exec.Command("rc-service", name, "status")
	output, err := cmd.Output()
	if err != nil {
		return StateUnknown, err
	}

	status := strings.TrimSpace(string(output))
	if strings.Contains(status, "started") {
		return StateRunning, nil
	}
	if strings.Contains(status, "stopped") {
		return StateStopped, nil
	}
	return StateUnknown, nil
}

func (o *openrcManager) Logs(name string, follow bool, lines int) (io.ReadCloser, error) {
	logPath := filepath.Join("/var/log", name+".log")

	if follow {
		// Use tail -f
		args := []string{"-f"}
		if lines > 0 {
			args = append([]string{"-n", fmt.Sprintf("%d", lines)}, args...)
		}
		args = append(args, logPath)

		cmd := exec.Command("tail", args...)
		pipe, err := cmd.StdoutPipe()
		if err != nil {
			return nil, err
		}

		if err := cmd.Start(); err != nil {
			return nil, err
		}

		return &cmdReadCloser{cmd, pipe}, nil
	}

	// Non-follow: read static content
	file, err := os.Open(logPath)
	if err != nil {
		return nil, err
	}

	return file, nil
}

// renderOpenrc renders the openrc unit template
func renderOpenrc(u Unit) (string, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/openrc.sh.tmpl")
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, u); err != nil {
		return "", err
	}

	return buf.String(), nil
}
