// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestOpenrcManagerRender(t *testing.T) {
	u := Unit{
		Name:        "test-agent",
		Description: "Test Agent Service",
		ExecPath:    "/usr/local/bin/test-agent",
		ExecArgs:    []string{"run", "--dir", "/var/lib/test"},
		User:        "testuser",
	}

	content, err := renderOpenrc(u)
	if err != nil {
		t.Fatalf("renderOpenrc() error = %v", err)
	}

	checks := []string{
		"#!/sbin/openrc-run",
		"description=\"Test Agent Service\"",
		"command=\"/usr/local/bin/test-agent\"",
		"command_user=\"testuser\"",
		"pidfile=\"/run/test-agent.pid\"",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("rendered template missing: %q\n\nGot:\n%s", check, content)
		}
	}
}

func TestOpenrcManagerInstall(t *testing.T) {
	unitDir := t.TempDir()
	mgr := &openrcManager{unitDir: unitDir}

	u := Unit{
		Name:        "test-service",
		Description: "Test Service",
		ExecPath:    "/bin/echo",
		ExecArgs:    []string{"hello"},
	}

	// Mock execRun to avoid actually calling rc-update
	oldExecRun := execRun
	defer func() { execRun = oldExecRun }()

	calls := []struct {
		name string
		args []string
	}{}

	execRun = func(name string, args ...string) error {
		calls = append(calls, struct {
			name string
			args []string
		}{name, args})
		return nil
	}

	// Install
	if err := mgr.Install(u); err != nil {
		t.Fatalf("Install() error = %v", err)
	}

	// Check script was written with executable bit
	scriptPath := filepath.Join(unitDir, "test-service")
	info, err := os.Stat(scriptPath)
	if err != nil {
		t.Fatalf("script not found: %v", err)
	}

	if (info.Mode() & 0755) != 0755 {
		t.Errorf("script not executable: %v", info.Mode())
	}

	// Check execRun was called with rc-update
	if len(calls) != 1 {
		t.Errorf("expected 1 execRun call, got %d: %v", len(calls), calls)
	}
	if calls[0].name != "rc-update" || len(calls[0].args) < 3 || calls[0].args[0] != "add" {
		t.Errorf("expected rc-update add call, got: %v", calls[0])
	}
}
