// Code generated by task; DO NOT EDIT.
//go:build !linux && !darwin

package service

import (
	"errors"
	"io"
)

type stubManager struct {
	kind string
}

func (s stubManager) Kind() string { return s.kind }

func (stubManager) Install(Unit) error {
	return errors.New("service: unsupported OS")
}

func (stubManager) Uninstall(string) error {
	return errors.New("service: unsupported OS")
}

func (stubManager) Start(string) error {
	return errors.New("service: unsupported OS")
}

func (stubManager) Stop(string) error {
	return errors.New("service: unsupported OS")
}

func (stubManager) Restart(string) error {
	return errors.New("service: unsupported OS")
}

func (stubManager) Status(string) (State, error) {
	return StateUnknown, errors.New("service: unsupported OS")
}

func (stubManager) Logs(string, bool, int) (io.ReadCloser, error) {
	return nil, errors.New("service: unsupported OS")
}

func newStub() Manager {
	return stubManager{kind: "stub"}
}

func newSystemd() Manager {
	return stubManager{kind: "systemd"}
}

func newOpenRC() Manager {
	return stubManager{kind: "openrc"}
}

func newSysV() Manager {
	return stubManager{kind: "sysv"}
}

func newLaunchd() Manager {
	return stubManager{kind: "launchd"}
}
