// Code generated by task; DO NOT EDIT.
//go:build darwin

package service

import (
	"errors"
	"io"
)

// systemd/openrc/sysv stubs for Darwin (unsupported)
type linuxStub struct {
	kind string
}

func (s linuxStub) Kind() string { return s.kind }

func (linuxStub) Install(Unit) error {
	return errors.New("service: init system not available on darwin")
}

func (linuxStub) Uninstall(string) error {
	return errors.New("service: init system not available on darwin")
}

func (linuxStub) Start(string) error {
	return errors.New("service: init system not available on darwin")
}

func (linuxStub) Stop(string) error {
	return errors.New("service: init system not available on darwin")
}

func (linuxStub) Restart(string) error {
	return errors.New("service: init system not available on darwin")
}

func (linuxStub) Status(string) (State, error) {
	return StateUnknown, errors.New("service: init system not available on darwin")
}

func (linuxStub) Logs(string, bool, int) (io.ReadCloser, error) {
	return nil, errors.New("service: init system not available on darwin")
}

func newSystemd() Manager {
	return linuxStub{kind: "systemd"}
}

func newOpenRC() Manager {
	return linuxStub{kind: "openrc"}
}

func newSysV() Manager {
	return linuxStub{kind: "sysv"}
}

// newStub returns an error-returning stub manager
type stubManager struct{}

func (stubManager) Kind() string { return "stub" }

func (stubManager) Install(Unit) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Uninstall(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Start(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Stop(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Restart(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Status(string) (State, error) {
	return StateUnknown, errors.New("service: no init system detected")
}

func (stubManager) Logs(string, bool, int) (io.ReadCloser, error) {
	return nil, errors.New("service: no init system detected")
}

func newStub() Manager {
	return stubManager{}
}

// Stub render functions for Linux init systems on Darwin
func renderSystemd(Unit) (string, error) {
	return "", nil
}

func renderOpenrc(Unit) (string, error) {
	return "", nil
}

func renderSysV(Unit) (string, error) {
	return "", nil
}
