// Code generated by task; DO NOT EDIT.
//go:build !linux && !darwin

package service

// Stub render functions for non-Linux/Darwin builds
func renderSystemd(Unit) (string, error) {
	return "", nil
}

func renderOpenrc(Unit) (string, error) {
	return "", nil
}

func renderSysV(Unit) (string, error) {
	return "", nil
}

func renderLaunchd(Unit) (string, error) {
	return "", nil
}
