// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"errors"
	"io"
)

// launchd stub for Linux (unsupported)
type launchdStub struct{}

func (launchdStub) Kind() string { return "launchd" }

func (launchdStub) Install(Unit) error {
	return errors.New("service: launchd not available on linux")
}

func (launchdStub) Uninstall(string) error {
	return errors.New("service: launchd not available on linux")
}

func (launchdStub) Start(string) error {
	return errors.New("service: launchd not available on linux")
}

func (launchdStub) Stop(string) error {
	return errors.New("service: launchd not available on linux")
}

func (launchdStub) Restart(string) error {
	return errors.New("service: launchd not available on linux")
}

func (launchdStub) Status(string) (State, error) {
	return StateUnknown, errors.New("service: launchd not available on linux")
}

func (launchdStub) Logs(string, bool, int) (io.ReadCloser, error) {
	return nil, errors.New("service: launchd not available on linux")
}

// newLaunchd returns stub on Linux
func newLaunchd() Manager {
	return launchdStub{}
}

// newStub returns an error-returning stub manager
type stubManager struct{}

func (stubManager) Kind() string { return "stub" }

func (stubManager) Install(Unit) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Uninstall(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Start(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Stop(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Restart(string) error {
	return errors.New("service: no init system detected")
}

func (stubManager) Status(string) (State, error) {
	return StateUnknown, errors.New("service: no init system detected")
}

func (stubManager) Logs(string, bool, int) (io.ReadCloser, error) {
	return nil, errors.New("service: no init system detected")
}

func newStub() Manager {
	return stubManager{}
}

// Stub render function for launchd on Linux
func renderLaunchd(Unit) (string, error) {
	return "", nil
}
