// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSystemdManagerRender(t *testing.T) {
	u := Unit{
		Name:        "test-agent",
		Description: "Test Agent Service",
		ExecPath:    "/usr/local/bin/test-agent",
		ExecArgs:    []string{"run", "--dir", "/var/lib/test"},
		User:        "testuser",
		Environment: map[string]string{
			"LOG_LEVEL": "debug",
		},
	}

	// Test rendering
	content, err := renderSystemd(u)
	if err != nil {
		t.Fatalf("renderSystemd() error = %v", err)
	}

	checks := []string{
		"[Unit]",
		"[Service]",
		"[Install]",
		"Description=Test Agent Service",
		"ExecStart=/usr/local/bin/test-agent run --dir /var/lib/test",
		"User=testuser",
		"Environment=\"LOG_LEVEL=debug\"",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("rendered template missing: %q\n\nGot:\n%s", check, content)
		}
	}
}

func TestSystemdManagerInstall(t *testing.T) {
	unitDir := t.TempDir()
	mgr := &systemdManager{unitDir: unitDir}

	u := Unit{
		Name:        "test-service",
		Description: "Test Service",
		ExecPath:    "/bin/echo",
		ExecArgs:    []string{"hello"},
	}

	// Mock execRun to avoid actually calling systemctl
	oldExecRun := execRun
	defer func() { execRun = oldExecRun }()

	calls := []struct {
		name string
		args []string
	}{}

	execRun = func(name string, args ...string) error {
		calls = append(calls, struct {
			name string
			args []string
		}{name, args})
		return nil
	}

	// Install
	if err := mgr.Install(u); err != nil {
		t.Fatalf("Install() error = %v", err)
	}

	// Check unit file was written
	unitPath := filepath.Join(unitDir, "test-service.service")
	content, err := os.ReadFile(unitPath)
	if err != nil {
		t.Fatalf("unit file not found: %v", err)
	}

	if !strings.Contains(string(content), "ExecStart=/bin/echo hello") {
		t.Errorf("unit file content incorrect: %s", string(content))
	}

	// Check execRun was called with daemon-reload and enable
	if len(calls) != 2 {
		t.Errorf("expected 2 execRun calls, got %d: %v", len(calls), calls)
	}
	if calls[0].name != "systemctl" || len(calls[0].args) < 1 || calls[0].args[0] != "daemon-reload" {
		t.Errorf("expected daemon-reload call, got: %v", calls[0])
	}
	if calls[1].name != "systemctl" || len(calls[1].args) < 2 || calls[1].args[0] != "enable" {
		t.Errorf("expected enable call, got: %v", calls[1])
	}
}
