// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"bytes"
	"embed"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

type systemdManager struct {
	unitDir string
}

func newSystemd() Manager {
	return &systemdManager{
		unitDir: "/etc/systemd/system",
	}
}

func (s *systemdManager) Kind() string {
	return "systemd"
}

func (s *systemdManager) Install(u Unit) error {
	content, err := renderSystemd(u)
	if err != nil {
		return fmt.Errorf("render systemd unit: %w", err)
	}

	unitPath := filepath.Join(s.unitDir, u.Name+".service")
	if err := os.WriteFile(unitPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write unit file: %w", err)
	}

	if err := execRun("systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("daemon-reload: %w", err)
	}

	if err := execRun("systemctl", "enable", u.Name); err != nil {
		return fmt.Errorf("enable: %w", err)
	}

	return nil
}

func (s *systemdManager) Uninstall(name string) error {
	if err := execRun("systemctl", "disable", name); err != nil {
		return fmt.Errorf("disable: %w", err)
	}

	unitPath := filepath.Join(s.unitDir, name+".service")
	if err := os.Remove(unitPath); err != nil {
		return fmt.Errorf("remove unit file: %w", err)
	}

	if err := execRun("systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("daemon-reload: %w", err)
	}

	return nil
}

func (s *systemdManager) Start(name string) error {
	return execRun("systemctl", "start", name)
}

func (s *systemdManager) Stop(name string) error {
	return execRun("systemctl", "stop", name)
}

func (s *systemdManager) Restart(name string) error {
	return execRun("systemctl", "restart", name)
}

func (s *systemdManager) Status(name string) (State, error) {
	cmd := exec.Command("systemctl", "is-active", name)
	output, err := cmd.Output()
	if err != nil {
		return StateUnknown, err
	}

	status := strings.TrimSpace(string(output))
	switch status {
	case "active":
		return StateRunning, nil
	case "inactive":
		return StateStopped, nil
	case "failed":
		return StateFailed, nil
	default:
		return StateUnknown, nil
	}
}

func (s *systemdManager) Logs(name string, follow bool, lines int) (io.ReadCloser, error) {
	args := []string{"-u", name}
	if follow {
		args = append(args, "-f")
	}
	if lines > 0 {
		args = append(args, "-n", strconv.Itoa(lines))
	}

	cmd := exec.Command("journalctl", args...)
	pipe, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}

	if err := cmd.Start(); err != nil {
		return nil, err
	}

	return &cmdReadCloser{cmd, pipe}, nil
}

// renderSystemd renders the systemd unit template
func renderSystemd(u Unit) (string, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/systemd.service.tmpl")
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, u); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// cmdReadCloser wraps an exec.Cmd and its stdout pipe
type cmdReadCloser struct {
	cmd  *exec.Cmd
	pipe io.ReadCloser
}

func (c *cmdReadCloser) Read(p []byte) (int, error) {
	return c.pipe.Read(p)
}

func (c *cmdReadCloser) Close() error {
	c.pipe.Close()
	return c.cmd.Wait()
}

// execRun is a package-level var that can be overridden in tests
var execRun = func(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	return cmd.Run()
}
