// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSysVManagerRender(t *testing.T) {
	u := Unit{
		Name:        "test-agent",
		Description: "Test Agent Service",
		ExecPath:    "/usr/local/bin/test-agent",
		ExecArgs:    []string{"run"},
	}

	content, err := renderSysV(u)
	if err != nil {
		t.Fatalf("renderSysV() error = %v", err)
	}

	checks := []string{
		"#!/bin/sh",
		"### BEGIN INIT INFO",
		"Provides:          test-agent",
		"DAEMON=/usr/local/bin/test-agent",
		"start-stop-daemon",
		"pidfile",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("rendered template missing: %q\n\nGot:\n%s", check, content)
		}
	}
}

func TestSysVManagerInstall(t *testing.T) {
	unitDir := t.TempDir()
	mgr := &sysVManager{unitDir: unitDir}

	u := Unit{
		Name:        "test-service",
		Description: "Test Service",
		ExecPath:    "/bin/echo",
		ExecArgs:    []string{"hello"},
	}

	// Mock execRun to avoid actually calling update-rc.d or chkconfig
	oldExecRun := execRun
	defer func() { execRun = oldExecRun }()

	calls := []struct {
		name string
		args []string
	}{}

	execRun = func(name string, args ...string) error {
		calls = append(calls, struct {
			name string
			args []string
		}{name, args})
		return nil
	}

	// Install
	if err := mgr.Install(u); err != nil {
		t.Fatalf("Install() error = %v", err)
	}

	// Check script was written with executable bit
	scriptPath := filepath.Join(unitDir, "test-service")
	info, err := os.Stat(scriptPath)
	if err != nil {
		t.Fatalf("script not found: %v", err)
	}

	if (info.Mode() & 0755) != 0755 {
		t.Errorf("script not executable: %v", info.Mode())
	}

	// Check execRun was called with update-rc.d
	if len(calls) != 1 {
		t.Errorf("expected 1 execRun call, got %d: %v", len(calls), calls)
	}
	if calls[0].name != "update-rc.d" || len(calls[0].args) < 2 || calls[0].args[1] != "defaults" {
		t.Errorf("expected update-rc.d defaults call, got: %v", calls[0])
	}
}
