// Code generated by task; DO NOT EDIT.
//go:build linux

package service

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

type sysVManager struct {
	unitDir string
}

func newSysV() Manager {
	return &sysVManager{
		unitDir: "/etc/init.d",
	}
}

func (s *sysVManager) Kind() string {
	return "sysv"
}

func (s *sysVManager) Install(u Unit) error {
	content, err := renderSysV(u)
	if err != nil {
		return fmt.Errorf("render sysv unit: %w", err)
	}

	scriptPath := filepath.Join(s.unitDir, u.Name)
	if err := os.WriteFile(scriptPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("write init script: %w", err)
	}

	// Try update-rc.d first (Debian), fallback to chkconfig (RHEL)
	err = execRun("update-rc.d", u.Name, "defaults")
	if err != nil {
		// Try chkconfig
		err = execRun("chkconfig", "--add", u.Name)
		if err != nil {
			return fmt.Errorf("failed to register init script: %w", err)
		}
	}

	return nil
}

func (s *sysVManager) Uninstall(name string) error {
	if err := execRun("service", name, "stop"); err != nil {
		// Ignore error if already stopped
		_ = err
	}

	// Try update-rc.d first (Debian), fallback to chkconfig (RHEL)
	err := execRun("update-rc.d", "-f", name, "remove")
	if err != nil {
		// Try chkconfig
		err = execRun("chkconfig", "--del", name)
		if err != nil {
			return fmt.Errorf("failed to unregister init script: %w", err)
		}
	}

	scriptPath := filepath.Join(s.unitDir, name)
	if err := os.Remove(scriptPath); err != nil {
		return fmt.Errorf("remove init script: %w", err)
	}

	return nil
}

func (s *sysVManager) Start(name string) error {
	return execRun("service", name, "start")
}

func (s *sysVManager) Stop(name string) error {
	return execRun("service", name, "stop")
}

func (s *sysVManager) Restart(name string) error {
	return execRun("service", name, "restart")
}

func (s *sysVManager) Status(name string) (State, error) {
	cmd := exec.Command("service", name, "status")
	output, err := cmd.Output()
	if err != nil {
		return StateUnknown, err
	}

	status := strings.TrimSpace(string(output))
	if strings.Contains(status, "running") {
		return StateRunning, nil
	}
	if strings.Contains(status, "stopped") {
		return StateStopped, nil
	}
	return StateUnknown, nil
}

func (s *sysVManager) Logs(name string, follow bool, lines int) (io.ReadCloser, error) {
	logPath := filepath.Join("/var/log", name+".log")

	if follow {
		args := []string{"-f"}
		if lines > 0 {
			args = append([]string{"-n", fmt.Sprintf("%d", lines)}, args...)
		}
		args = append(args, logPath)

		cmd := exec.Command("tail", args...)
		pipe, err := cmd.StdoutPipe()
		if err != nil {
			return nil, err
		}

		if err := cmd.Start(); err != nil {
			return nil, err
		}

		return &cmdReadCloser{cmd, pipe}, nil
	}

	file, err := os.Open(logPath)
	if err != nil {
		return nil, err
	}

	return file, nil
}

// renderSysV renders the sysv unit template
func renderSysV(u Unit) (string, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/sysv.sh.tmpl")
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, u); err != nil {
		return "", err
	}

	return buf.String(), nil
}
