// Code generated by task; DO NOT EDIT.
//go:build darwin

package service

import (
	"strings"
	"testing"
)

func TestRenderLaunchdTemplate(t *testing.T) {
	u := Unit{
		Name:        "test-agent",
		Description: "Test Agent Service",
		ExecPath:    "/usr/local/bin/test-agent",
		ExecArgs:    []string{"run", "--debug"},
		User:        "testuser",
	}

	content, err := renderLaunchd(u)
	if err != nil {
		t.Fatalf("renderLaunchd() error = %v", err)
	}

	checks := []string{
		"com.hlhelper.test-agent",
		"/usr/local/bin/test-agent",
		"run",
		"--debug",
		"<true/>",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("rendered template missing: %q", check)
		}
	}
}
