// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: fleet/v1/agent_bridge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentBridge_Stream_FullMethodName = "/fleet.v1.AgentBridge/Stream"
)

// AgentBridgeClient is the client API for AgentBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentBridgeClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error)
}

type agentBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentBridgeClient(cc grpc.ClientConnInterface) AgentBridgeClient {
	return &agentBridgeClient{cc}
}

func (c *agentBridgeClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentBridge_ServiceDesc.Streams[0], AgentBridge_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToServer, ServerToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentBridge_StreamClient = grpc.BidiStreamingClient[AgentToServer, ServerToAgent]

// AgentBridgeServer is the server API for AgentBridge service.
// All implementations must embed UnimplementedAgentBridgeServer
// for forward compatibility.
type AgentBridgeServer interface {
	Stream(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error
	mustEmbedUnimplementedAgentBridgeServer()
}

// UnimplementedAgentBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentBridgeServer struct{}

func (UnimplementedAgentBridgeServer) Stream(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentBridgeServer) mustEmbedUnimplementedAgentBridgeServer() {}
func (UnimplementedAgentBridgeServer) testEmbeddedByValue()                     {}

// UnsafeAgentBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentBridgeServer will
// result in compilation errors.
type UnsafeAgentBridgeServer interface {
	mustEmbedUnimplementedAgentBridgeServer()
}

func RegisterAgentBridgeServer(s grpc.ServiceRegistrar, srv AgentBridgeServer) {
	// If the following call panics, it indicates UnimplementedAgentBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentBridge_ServiceDesc, srv)
}

func _AgentBridge_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentBridgeServer).Stream(&grpc.GenericServerStream[AgentToServer, ServerToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentBridge_StreamServer = grpc.BidiStreamingServer[AgentToServer, ServerToAgent]

// AgentBridge_ServiceDesc is the grpc.ServiceDesc for AgentBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.AgentBridge",
	HandlerType: (*AgentBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentBridge_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fleet/v1/agent_bridge.proto",
}
