// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet/v1/agent_bridge.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat_AgentUpdateStatus int32

const (
	Heartbeat_AGENT_UPDATE_STATUS_UNSPECIFIED    Heartbeat_AgentUpdateStatus = 0
	Heartbeat_AGENT_UPDATE_STATUS_IDLE           Heartbeat_AgentUpdateStatus = 1
	Heartbeat_AGENT_UPDATE_STATUS_DOWNLOADING    Heartbeat_AgentUpdateStatus = 2
	Heartbeat_AGENT_UPDATE_STATUS_SWAPPING       Heartbeat_AgentUpdateStatus = 3
	Heartbeat_AGENT_UPDATE_STATUS_HEALTHCHECKING Heartbeat_AgentUpdateStatus = 4
	Heartbeat_AGENT_UPDATE_STATUS_ROLLED_BACK    Heartbeat_AgentUpdateStatus = 5
	Heartbeat_AGENT_UPDATE_STATUS_FAILED         Heartbeat_AgentUpdateStatus = 6
)

// Enum value maps for Heartbeat_AgentUpdateStatus.
var (
	Heartbeat_AgentUpdateStatus_name = map[int32]string{
		0: "AGENT_UPDATE_STATUS_UNSPECIFIED",
		1: "AGENT_UPDATE_STATUS_IDLE",
		2: "AGENT_UPDATE_STATUS_DOWNLOADING",
		3: "AGENT_UPDATE_STATUS_SWAPPING",
		4: "AGENT_UPDATE_STATUS_HEALTHCHECKING",
		5: "AGENT_UPDATE_STATUS_ROLLED_BACK",
		6: "AGENT_UPDATE_STATUS_FAILED",
	}
	Heartbeat_AgentUpdateStatus_value = map[string]int32{
		"AGENT_UPDATE_STATUS_UNSPECIFIED":    0,
		"AGENT_UPDATE_STATUS_IDLE":           1,
		"AGENT_UPDATE_STATUS_DOWNLOADING":    2,
		"AGENT_UPDATE_STATUS_SWAPPING":       3,
		"AGENT_UPDATE_STATUS_HEALTHCHECKING": 4,
		"AGENT_UPDATE_STATUS_ROLLED_BACK":    5,
		"AGENT_UPDATE_STATUS_FAILED":         6,
	}
)

func (x Heartbeat_AgentUpdateStatus) Enum() *Heartbeat_AgentUpdateStatus {
	p := new(Heartbeat_AgentUpdateStatus)
	*p = x
	return p
}

func (x Heartbeat_AgentUpdateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Heartbeat_AgentUpdateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_agent_bridge_proto_enumTypes[0].Descriptor()
}

func (Heartbeat_AgentUpdateStatus) Type() protoreflect.EnumType {
	return &file_fleet_v1_agent_bridge_proto_enumTypes[0]
}

func (x Heartbeat_AgentUpdateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Heartbeat_AgentUpdateStatus.Descriptor instead.
func (Heartbeat_AgentUpdateStatus) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{6, 0}
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mount         string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Disk) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *Disk) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type Nic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ipv4          []string               `protobuf:"bytes,3,rep,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          []string               `protobuf:"bytes,4,rep,name=ipv6,proto3" json:"ipv6,omitempty"`
	SpeedMbps     uint64                 `protobuf:"varint,5,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nic) Reset() {
	*x = Nic{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nic.ProtoReflect.Descriptor instead.
func (*Nic) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Nic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nic) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Nic) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *Nic) GetIpv6() []string {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

func (x *Nic) GetSpeedMbps() uint64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

type HostSurvey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Kernel        string                 `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Virt          string                 `protobuf:"bytes,6,opt,name=virt,proto3" json:"virt,omitempty"`
	CpuModel      string                 `protobuf:"bytes,7,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,8,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads    uint32                 `protobuf:"varint,9,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	MemTotalBytes uint64                 `protobuf:"varint,10,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,11,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics          []*Nic                 `protobuf:"bytes,12,rep,name=nics,proto3" json:"nics,omitempty"`
	BiosVendor    string                 `protobuf:"bytes,13,opt,name=bios_vendor,json=biosVendor,proto3" json:"bios_vendor,omitempty"`
	BiosVersion   string                 `protobuf:"bytes,14,opt,name=bios_version,json=biosVersion,proto3" json:"bios_version,omitempty"`
	BoardVendor   string                 `protobuf:"bytes,15,opt,name=board_vendor,json=boardVendor,proto3" json:"board_vendor,omitempty"`
	BoardProduct  string                 `protobuf:"bytes,16,opt,name=board_product,json=boardProduct,proto3" json:"board_product,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Signature     []byte                 `protobuf:"bytes,200,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSurvey) Reset() {
	*x = HostSurvey{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSurvey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSurvey) ProtoMessage() {}

func (x *HostSurvey) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSurvey.ProtoReflect.Descriptor instead.
func (*HostSurvey) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *HostSurvey) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostSurvey) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostSurvey) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HostSurvey) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HostSurvey) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostSurvey) GetVirt() string {
	if x != nil {
		return x.Virt
	}
	return ""
}

func (x *HostSurvey) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HostSurvey) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostSurvey) GetCpuThreads() uint32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *HostSurvey) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *HostSurvey) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HostSurvey) GetNics() []*Nic {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *HostSurvey) GetBiosVendor() string {
	if x != nil {
		return x.BiosVendor
	}
	return ""
}

func (x *HostSurvey) GetBiosVersion() string {
	if x != nil {
		return x.BiosVersion
	}
	return ""
}

func (x *HostSurvey) GetBoardVendor() string {
	if x != nil {
		return x.BoardVendor
	}
	return ""
}

func (x *HostSurvey) GetBoardProduct() string {
	if x != nil {
		return x.BoardProduct
	}
	return ""
}

func (x *HostSurvey) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *HostSurvey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HeartbeatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalS     uint32                 `protobuf:"varint,1,opt,name=interval_s,json=intervalS,proto3" json:"interval_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatConfig) Reset() {
	*x = HeartbeatConfig{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatConfig) ProtoMessage() {}

func (x *HeartbeatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatConfig.ProtoReflect.Descriptor instead.
func (*HeartbeatConfig) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatConfig) GetIntervalS() uint32 {
	if x != nil {
		return x.IntervalS
	}
	return 0
}

type RunSurvey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSurvey) Reset() {
	*x = RunSurvey{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSurvey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSurvey) ProtoMessage() {}

func (x *RunSurvey) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSurvey.ProtoReflect.Descriptor instead.
func (*RunSurvey) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *RunSurvey) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HostMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load_1        float32                `protobuf:"fixed32,1,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5        float32                `protobuf:"fixed32,2,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15       float32                `protobuf:"fixed32,3,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	MemUsedPct    float32                `protobuf:"fixed32,4,opt,name=mem_used_pct,json=memUsedPct,proto3" json:"mem_used_pct,omitempty"`
	DiskUsedPct   float32                `protobuf:"fixed32,5,opt,name=disk_used_pct,json=diskUsedPct,proto3" json:"disk_used_pct,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	NetRxBps      uint64                 `protobuf:"varint,7,opt,name=net_rx_bps,json=netRxBps,proto3" json:"net_rx_bps,omitempty"` // bytes/sec received, averaged over heartbeat interval
	NetTxBps      uint64                 `protobuf:"varint,8,opt,name=net_tx_bps,json=netTxBps,proto3" json:"net_tx_bps,omitempty"` // bytes/sec transmitted, averaged over heartbeat interval
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *HostMetrics) GetLoad_1() float32 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *HostMetrics) GetLoad_5() float32 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *HostMetrics) GetLoad_15() float32 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *HostMetrics) GetMemUsedPct() float32 {
	if x != nil {
		return x.MemUsedPct
	}
	return 0
}

func (x *HostMetrics) GetDiskUsedPct() float32 {
	if x != nil {
		return x.DiskUsedPct
	}
	return 0
}

func (x *HostMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HostMetrics) GetNetRxBps() uint64 {
	if x != nil {
		return x.NetRxBps
	}
	return 0
}

func (x *HostMetrics) GetNetTxBps() uint64 {
	if x != nil {
		return x.NetTxBps
	}
	return 0
}

type Heartbeat struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	HostId              string                      `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	At                  *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	LastAckedSeq        uint64                      `protobuf:"varint,3,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	Metrics             *HostMetrics                `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	AgentVersion        string                      `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UpdateStatus        Heartbeat_AgentUpdateStatus `protobuf:"varint,6,opt,name=update_status,json=updateStatus,proto3,enum=fleet.v1.Heartbeat_AgentUpdateStatus" json:"update_status,omitempty"`
	UpdateTargetVersion string                      `protobuf:"bytes,7,opt,name=update_target_version,json=updateTargetVersion,proto3" json:"update_target_version,omitempty"`
	Signature           []byte                      `protobuf:"bytes,200,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Heartbeat) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Heartbeat) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

func (x *Heartbeat) GetMetrics() *HostMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Heartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Heartbeat) GetUpdateStatus() Heartbeat_AgentUpdateStatus {
	if x != nil {
		return x.UpdateStatus
	}
	return Heartbeat_AGENT_UPDATE_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetUpdateTargetVersion() string {
	if x != nil {
		return x.UpdateTargetVersion
	}
	return ""
}

func (x *Heartbeat) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HeartbeatAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_at,json=serverAt,proto3" json:"server_at,omitempty"`
	NextExpectedSeq uint64                 `protobuf:"varint,2,opt,name=next_expected_seq,json=nextExpectedSeq,proto3" json:"next_expected_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetServerAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerAt
	}
	return nil
}

func (x *HeartbeatAck) GetNextExpectedSeq() uint64 {
	if x != nil {
		return x.NextExpectedSeq
	}
	return 0
}

type ResumeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	StreamSessionId string                 `protobuf:"bytes,2,opt,name=stream_session_id,json=streamSessionId,proto3" json:"stream_session_id,omitempty"`
	LastSeq         uint64                 `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ResumeRequest) GetStreamSessionId() string {
	if x != nil {
		return x.StreamSessionId
	}
	return ""
}

func (x *ResumeRequest) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *CapabilityRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CapabilityRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type CertRotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRotateRequest) Reset() {
	*x = CertRotateRequest{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRotateRequest) ProtoMessage() {}

func (x *CertRotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRotateRequest.ProtoReflect.Descriptor instead.
func (*CertRotateRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *CertRotateRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CertRotateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type CertIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertChainPem  []byte                 `protobuf:"bytes,1,opt,name=cert_chain_pem,json=certChainPem,proto3" json:"cert_chain_pem,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertIssueResponse) Reset() {
	*x = CertIssueResponse{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertIssueResponse) ProtoMessage() {}

func (x *CertIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertIssueResponse.ProtoReflect.Descriptor instead.
func (*CertIssueResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *CertIssueResponse) GetCertChainPem() []byte {
	if x != nil {
		return x.CertChainPem
	}
	return nil
}

func (x *CertIssueResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type ManifestUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManifestSigned []byte                 `protobuf:"bytes,1,opt,name=manifest_signed,json=manifestSigned,proto3" json:"manifest_signed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManifestUpdate) Reset() {
	*x = ManifestUpdate{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestUpdate) ProtoMessage() {}

func (x *ManifestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestUpdate.ProtoReflect.Descriptor instead.
func (*ManifestUpdate) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *ManifestUpdate) GetManifestSigned() []byte {
	if x != nil {
		return x.ManifestSigned
	}
	return nil
}

type Decommission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decommission) Reset() {
	*x = Decommission{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decommission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decommission) ProtoMessage() {}

func (x *Decommission) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decommission.ProtoReflect.Descriptor instead.
func (*Decommission) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *Decommission) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decommission) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type DecommissionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionAck) Reset() {
	*x = DecommissionAck{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionAck) ProtoMessage() {}

func (x *DecommissionAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionAck.ProtoReflect.Descriptor instead.
func (*DecommissionAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *DecommissionAck) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_Result
	//	*AgentToServer_Resume
	//	*AgentToServer_CapReq
	//	*AgentToServer_CertRotate
	//	*AgentToServer_DecomAck
	//	*AgentToServer_HostSurvey
	Msg           isAgentToServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *AgentToServer) GetMsg() isAgentToServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetResult() *ResultEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentToServer) GetResume() *ResumeRequest {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *AgentToServer) GetCapReq() *CapabilityRequest {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_CapReq); ok {
			return x.CapReq
		}
	}
	return nil
}

func (x *AgentToServer) GetCertRotate() *CertRotateRequest {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_CertRotate); ok {
			return x.CertRotate
		}
	}
	return nil
}

func (x *AgentToServer) GetDecomAck() *DecommissionAck {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_DecomAck); ok {
			return x.DecomAck
		}
	}
	return nil
}

func (x *AgentToServer) GetHostSurvey() *HostSurvey {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_HostSurvey); ok {
			return x.HostSurvey
		}
	}
	return nil
}

type isAgentToServer_Msg interface {
	isAgentToServer_Msg()
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_Result struct {
	Result *ResultEnvelope `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type AgentToServer_Resume struct {
	Resume *ResumeRequest `protobuf:"bytes,3,opt,name=resume,proto3,oneof"`
}

type AgentToServer_CapReq struct {
	CapReq *CapabilityRequest `protobuf:"bytes,4,opt,name=cap_req,json=capReq,proto3,oneof"`
}

type AgentToServer_CertRotate struct {
	CertRotate *CertRotateRequest `protobuf:"bytes,5,opt,name=cert_rotate,json=certRotate,proto3,oneof"`
}

type AgentToServer_DecomAck struct {
	DecomAck *DecommissionAck `protobuf:"bytes,6,opt,name=decom_ack,json=decomAck,proto3,oneof"`
}

type AgentToServer_HostSurvey struct {
	HostSurvey *HostSurvey `protobuf:"bytes,7,opt,name=host_survey,json=hostSurvey,proto3,oneof"`
}

func (*AgentToServer_Heartbeat) isAgentToServer_Msg() {}

func (*AgentToServer_Result) isAgentToServer_Msg() {}

func (*AgentToServer_Resume) isAgentToServer_Msg() {}

func (*AgentToServer_CapReq) isAgentToServer_Msg() {}

func (*AgentToServer_CertRotate) isAgentToServer_Msg() {}

func (*AgentToServer_DecomAck) isAgentToServer_Msg() {}

func (*AgentToServer_HostSurvey) isAgentToServer_Msg() {}

type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerToAgent_Command
	//	*ServerToAgent_HbAck
	//	*ServerToAgent_CertIssue
	//	*ServerToAgent_Manifest
	//	*ServerToAgent_Decom
	//	*ServerToAgent_HbConfig
	//	*ServerToAgent_RunSurvey
	Msg           isServerToAgent_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *ServerToAgent) GetMsg() isServerToAgent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerToAgent) GetCommand() *CommandEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerToAgent) GetHbAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_HbAck); ok {
			return x.HbAck
		}
	}
	return nil
}

func (x *ServerToAgent) GetCertIssue() *CertIssueResponse {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_CertIssue); ok {
			return x.CertIssue
		}
	}
	return nil
}

func (x *ServerToAgent) GetManifest() *ManifestUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *ServerToAgent) GetDecom() *Decommission {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Decom); ok {
			return x.Decom
		}
	}
	return nil
}

func (x *ServerToAgent) GetHbConfig() *HeartbeatConfig {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_HbConfig); ok {
			return x.HbConfig
		}
	}
	return nil
}

func (x *ServerToAgent) GetRunSurvey() *RunSurvey {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_RunSurvey); ok {
			return x.RunSurvey
		}
	}
	return nil
}

type isServerToAgent_Msg interface {
	isServerToAgent_Msg()
}

type ServerToAgent_Command struct {
	Command *CommandEnvelope `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerToAgent_HbAck struct {
	HbAck *HeartbeatAck `protobuf:"bytes,2,opt,name=hb_ack,json=hbAck,proto3,oneof"`
}

type ServerToAgent_CertIssue struct {
	CertIssue *CertIssueResponse `protobuf:"bytes,3,opt,name=cert_issue,json=certIssue,proto3,oneof"`
}

type ServerToAgent_Manifest struct {
	Manifest *ManifestUpdate `protobuf:"bytes,4,opt,name=manifest,proto3,oneof"`
}

type ServerToAgent_Decom struct {
	Decom *Decommission `protobuf:"bytes,5,opt,name=decom,proto3,oneof"`
}

type ServerToAgent_HbConfig struct {
	HbConfig *HeartbeatConfig `protobuf:"bytes,6,opt,name=hb_config,json=hbConfig,proto3,oneof"`
}

type ServerToAgent_RunSurvey struct {
	RunSurvey *RunSurvey `protobuf:"bytes,7,opt,name=run_survey,json=runSurvey,proto3,oneof"`
}

func (*ServerToAgent_Command) isServerToAgent_Msg() {}

func (*ServerToAgent_HbAck) isServerToAgent_Msg() {}

func (*ServerToAgent_CertIssue) isServerToAgent_Msg() {}

func (*ServerToAgent_Manifest) isServerToAgent_Msg() {}

func (*ServerToAgent_Decom) isServerToAgent_Msg() {}

func (*ServerToAgent_HbConfig) isServerToAgent_Msg() {}

func (*ServerToAgent_RunSurvey) isServerToAgent_Msg() {}

var File_fleet_v1_agent_bridge_proto protoreflect.FileDescriptor

const file_fleet_v1_agent_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1bfleet/v1/agent_bridge.proto\x12\bfleet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17fleet/v1/envelope.proto\x1a\x16fleet/v1/results.proto\"k\n" +
	"\x04Disk\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\"r\n" +
	"\x03Nic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x12\n" +
	"\x04ipv4\x18\x03 \x03(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x04 \x03(\tR\x04ipv6\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x05 \x01(\x04R\tspeedMbps\"\xca\x04\n" +
	"\n" +
	"HostSurvey\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x12\n" +
	"\x04virt\x18\x06 \x01(\tR\x04virt\x12\x1b\n" +
	"\tcpu_model\x18\a \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\b \x01(\rR\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\t \x01(\rR\n" +
	"cpuThreads\x12&\n" +
	"\x0fmem_total_bytes\x18\n" +
	" \x01(\x04R\rmemTotalBytes\x12$\n" +
	"\x05disks\x18\v \x03(\v2\x0e.fleet.v1.DiskR\x05disks\x12!\n" +
	"\x04nics\x18\f \x03(\v2\r.fleet.v1.NicR\x04nics\x12\x1f\n" +
	"\vbios_vendor\x18\r \x01(\tR\n" +
	"biosVendor\x12!\n" +
	"\fbios_version\x18\x0e \x01(\tR\vbiosVersion\x12!\n" +
	"\fboard_vendor\x18\x0f \x01(\tR\vboardVendor\x12#\n" +
	"\rboard_product\x18\x10 \x01(\tR\fboardProduct\x12=\n" +
	"\fcollected_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12\x1d\n" +
	"\tsignature\x18\xc8\x01 \x01(\fR\tsignature\"0\n" +
	"\x0fHeartbeatConfig\x12\x1d\n" +
	"\n" +
	"interval_s\x18\x01 \x01(\rR\tintervalS\"#\n" +
	"\tRunSurvey\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xfd\x01\n" +
	"\vHostMetrics\x12\x15\n" +
	"\x06load_1\x18\x01 \x01(\x02R\x05load1\x12\x15\n" +
	"\x06load_5\x18\x02 \x01(\x02R\x05load5\x12\x17\n" +
	"\aload_15\x18\x03 \x01(\x02R\x06load15\x12 \n" +
	"\fmem_used_pct\x18\x04 \x01(\x02R\n" +
	"memUsedPct\x12\"\n" +
	"\rdisk_used_pct\x18\x05 \x01(\x02R\vdiskUsedPct\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\x12\x1c\n" +
	"\n" +
	"net_rx_bps\x18\a \x01(\x04R\bnetRxBps\x12\x1c\n" +
	"\n" +
	"net_tx_bps\x18\b \x01(\x04R\bnetTxBps\"\xf8\x04\n" +
	"\tHeartbeat\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12$\n" +
	"\x0elast_acked_seq\x18\x03 \x01(\x04R\flastAckedSeq\x12/\n" +
	"\ametrics\x18\x04 \x01(\v2\x15.fleet.v1.HostMetricsR\ametrics\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12J\n" +
	"\rupdate_status\x18\x06 \x01(\x0e2%.fleet.v1.Heartbeat.AgentUpdateStatusR\fupdateStatus\x122\n" +
	"\x15update_target_version\x18\a \x01(\tR\x13updateTargetVersion\x12\x1d\n" +
	"\tsignature\x18\xc8\x01 \x01(\fR\tsignature\"\x8a\x02\n" +
	"\x11AgentUpdateStatus\x12#\n" +
	"\x1fAGENT_UPDATE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AGENT_UPDATE_STATUS_IDLE\x10\x01\x12#\n" +
	"\x1fAGENT_UPDATE_STATUS_DOWNLOADING\x10\x02\x12 \n" +
	"\x1cAGENT_UPDATE_STATUS_SWAPPING\x10\x03\x12&\n" +
	"\"AGENT_UPDATE_STATUS_HEALTHCHECKING\x10\x04\x12#\n" +
	"\x1fAGENT_UPDATE_STATUS_ROLLED_BACK\x10\x05\x12\x1e\n" +
	"\x1aAGENT_UPDATE_STATUS_FAILED\x10\x06\"s\n" +
	"\fHeartbeatAck\x127\n" +
	"\tserver_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bserverAt\x12*\n" +
	"\x11next_expected_seq\x18\x02 \x01(\x04R\x0fnextExpectedSeq\"o\n" +
	"\rResumeRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x11stream_session_id\x18\x02 \x01(\tR\x0fstreamSessionId\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x04R\alastSeq\"B\n" +
	"\x11CapabilityRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"E\n" +
	"\x11CertRotateRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\"r\n" +
	"\x11CertIssueResponse\x12$\n" +
	"\x0ecert_chain_pem\x18\x01 \x01(\fR\fcertChainPem\x127\n" +
	"\tnot_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"9\n" +
	"\x0eManifestUpdate\x12'\n" +
	"\x0fmanifest_signed\x18\x01 \x01(\fR\x0emanifestSigned\"I\n" +
	"\fDecommission\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12!\n" +
	"\frequested_by\x18\x02 \x01(\tR\vrequestedBy\"=\n" +
	"\x0fDecommissionAck\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\x9d\x03\n" +
	"\rAgentToServer\x123\n" +
	"\theartbeat\x18\x01 \x01(\v2\x13.fleet.v1.HeartbeatH\x00R\theartbeat\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.fleet.v1.ResultEnvelopeH\x00R\x06result\x121\n" +
	"\x06resume\x18\x03 \x01(\v2\x17.fleet.v1.ResumeRequestH\x00R\x06resume\x126\n" +
	"\acap_req\x18\x04 \x01(\v2\x1b.fleet.v1.CapabilityRequestH\x00R\x06capReq\x12>\n" +
	"\vcert_rotate\x18\x05 \x01(\v2\x1b.fleet.v1.CertRotateRequestH\x00R\n" +
	"certRotate\x128\n" +
	"\tdecom_ack\x18\x06 \x01(\v2\x19.fleet.v1.DecommissionAckH\x00R\bdecomAck\x127\n" +
	"\vhost_survey\x18\a \x01(\v2\x14.fleet.v1.HostSurveyH\x00R\n" +
	"hostSurveyB\x05\n" +
	"\x03msg\"\x94\x03\n" +
	"\rServerToAgent\x125\n" +
	"\acommand\x18\x01 \x01(\v2\x19.fleet.v1.CommandEnvelopeH\x00R\acommand\x12/\n" +
	"\x06hb_ack\x18\x02 \x01(\v2\x16.fleet.v1.HeartbeatAckH\x00R\x05hbAck\x12<\n" +
	"\n" +
	"cert_issue\x18\x03 \x01(\v2\x1b.fleet.v1.CertIssueResponseH\x00R\tcertIssue\x126\n" +
	"\bmanifest\x18\x04 \x01(\v2\x18.fleet.v1.ManifestUpdateH\x00R\bmanifest\x12.\n" +
	"\x05decom\x18\x05 \x01(\v2\x16.fleet.v1.DecommissionH\x00R\x05decom\x128\n" +
	"\thb_config\x18\x06 \x01(\v2\x19.fleet.v1.HeartbeatConfigH\x00R\bhbConfig\x124\n" +
	"\n" +
	"run_survey\x18\a \x01(\v2\x13.fleet.v1.RunSurveyH\x00R\trunSurveyB\x05\n" +
	"\x03msg2M\n" +
	"\vAgentBridge\x12>\n" +
	"\x06Stream\x12\x17.fleet.v1.AgentToServer\x1a\x17.fleet.v1.ServerToAgent(\x010\x01B-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3"

var (
	file_fleet_v1_agent_bridge_proto_rawDescOnce sync.Once
	file_fleet_v1_agent_bridge_proto_rawDescData []byte
)

func file_fleet_v1_agent_bridge_proto_rawDescGZIP() []byte {
	file_fleet_v1_agent_bridge_proto_rawDescOnce.Do(func() {
		file_fleet_v1_agent_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_agent_bridge_proto_rawDesc), len(file_fleet_v1_agent_bridge_proto_rawDesc)))
	})
	return file_fleet_v1_agent_bridge_proto_rawDescData
}

var file_fleet_v1_agent_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fleet_v1_agent_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fleet_v1_agent_bridge_proto_goTypes = []any{
	(Heartbeat_AgentUpdateStatus)(0), // 0: fleet.v1.Heartbeat.AgentUpdateStatus
	(*Disk)(nil),                     // 1: fleet.v1.Disk
	(*Nic)(nil),                      // 2: fleet.v1.Nic
	(*HostSurvey)(nil),               // 3: fleet.v1.HostSurvey
	(*HeartbeatConfig)(nil),          // 4: fleet.v1.HeartbeatConfig
	(*RunSurvey)(nil),                // 5: fleet.v1.RunSurvey
	(*HostMetrics)(nil),              // 6: fleet.v1.HostMetrics
	(*Heartbeat)(nil),                // 7: fleet.v1.Heartbeat
	(*HeartbeatAck)(nil),             // 8: fleet.v1.HeartbeatAck
	(*ResumeRequest)(nil),            // 9: fleet.v1.ResumeRequest
	(*CapabilityRequest)(nil),        // 10: fleet.v1.CapabilityRequest
	(*CertRotateRequest)(nil),        // 11: fleet.v1.CertRotateRequest
	(*CertIssueResponse)(nil),        // 12: fleet.v1.CertIssueResponse
	(*ManifestUpdate)(nil),           // 13: fleet.v1.ManifestUpdate
	(*Decommission)(nil),             // 14: fleet.v1.Decommission
	(*DecommissionAck)(nil),          // 15: fleet.v1.DecommissionAck
	(*AgentToServer)(nil),            // 16: fleet.v1.AgentToServer
	(*ServerToAgent)(nil),            // 17: fleet.v1.ServerToAgent
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
	(*ResultEnvelope)(nil),           // 19: fleet.v1.ResultEnvelope
	(*CommandEnvelope)(nil),          // 20: fleet.v1.CommandEnvelope
}
var file_fleet_v1_agent_bridge_proto_depIdxs = []int32{
	1,  // 0: fleet.v1.HostSurvey.disks:type_name -> fleet.v1.Disk
	2,  // 1: fleet.v1.HostSurvey.nics:type_name -> fleet.v1.Nic
	18, // 2: fleet.v1.HostSurvey.collected_at:type_name -> google.protobuf.Timestamp
	18, // 3: fleet.v1.Heartbeat.at:type_name -> google.protobuf.Timestamp
	6,  // 4: fleet.v1.Heartbeat.metrics:type_name -> fleet.v1.HostMetrics
	0,  // 5: fleet.v1.Heartbeat.update_status:type_name -> fleet.v1.Heartbeat.AgentUpdateStatus
	18, // 6: fleet.v1.HeartbeatAck.server_at:type_name -> google.protobuf.Timestamp
	18, // 7: fleet.v1.CertIssueResponse.not_after:type_name -> google.protobuf.Timestamp
	18, // 8: fleet.v1.DecommissionAck.at:type_name -> google.protobuf.Timestamp
	7,  // 9: fleet.v1.AgentToServer.heartbeat:type_name -> fleet.v1.Heartbeat
	19, // 10: fleet.v1.AgentToServer.result:type_name -> fleet.v1.ResultEnvelope
	9,  // 11: fleet.v1.AgentToServer.resume:type_name -> fleet.v1.ResumeRequest
	10, // 12: fleet.v1.AgentToServer.cap_req:type_name -> fleet.v1.CapabilityRequest
	11, // 13: fleet.v1.AgentToServer.cert_rotate:type_name -> fleet.v1.CertRotateRequest
	15, // 14: fleet.v1.AgentToServer.decom_ack:type_name -> fleet.v1.DecommissionAck
	3,  // 15: fleet.v1.AgentToServer.host_survey:type_name -> fleet.v1.HostSurvey
	20, // 16: fleet.v1.ServerToAgent.command:type_name -> fleet.v1.CommandEnvelope
	8,  // 17: fleet.v1.ServerToAgent.hb_ack:type_name -> fleet.v1.HeartbeatAck
	12, // 18: fleet.v1.ServerToAgent.cert_issue:type_name -> fleet.v1.CertIssueResponse
	13, // 19: fleet.v1.ServerToAgent.manifest:type_name -> fleet.v1.ManifestUpdate
	14, // 20: fleet.v1.ServerToAgent.decom:type_name -> fleet.v1.Decommission
	4,  // 21: fleet.v1.ServerToAgent.hb_config:type_name -> fleet.v1.HeartbeatConfig
	5,  // 22: fleet.v1.ServerToAgent.run_survey:type_name -> fleet.v1.RunSurvey
	16, // 23: fleet.v1.AgentBridge.Stream:input_type -> fleet.v1.AgentToServer
	17, // 24: fleet.v1.AgentBridge.Stream:output_type -> fleet.v1.ServerToAgent
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_fleet_v1_agent_bridge_proto_init() }
func file_fleet_v1_agent_bridge_proto_init() {
	if File_fleet_v1_agent_bridge_proto != nil {
		return
	}
	file_fleet_v1_envelope_proto_init()
	file_fleet_v1_results_proto_init()
	file_fleet_v1_agent_bridge_proto_msgTypes[15].OneofWrappers = []any{
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_Result)(nil),
		(*AgentToServer_Resume)(nil),
		(*AgentToServer_CapReq)(nil),
		(*AgentToServer_CertRotate)(nil),
		(*AgentToServer_DecomAck)(nil),
		(*AgentToServer_HostSurvey)(nil),
	}
	file_fleet_v1_agent_bridge_proto_msgTypes[16].OneofWrappers = []any{
		(*ServerToAgent_Command)(nil),
		(*ServerToAgent_HbAck)(nil),
		(*ServerToAgent_CertIssue)(nil),
		(*ServerToAgent_Manifest)(nil),
		(*ServerToAgent_Decom)(nil),
		(*ServerToAgent_HbConfig)(nil),
		(*ServerToAgent_RunSurvey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_agent_bridge_proto_rawDesc), len(file_fleet_v1_agent_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_v1_agent_bridge_proto_goTypes,
		DependencyIndexes: file_fleet_v1_agent_bridge_proto_depIdxs,
		EnumInfos:         file_fleet_v1_agent_bridge_proto_enumTypes,
		MessageInfos:      file_fleet_v1_agent_bridge_proto_msgTypes,
	}.Build()
	File_fleet_v1_agent_bridge_proto = out.File
	file_fleet_v1_agent_bridge_proto_goTypes = nil
	file_fleet_v1_agent_bridge_proto_depIdxs = nil
}
