// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet/v1/commands.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransfer_Dir int32

const (
	FileTransfer_UPLOAD   FileTransfer_Dir = 0
	FileTransfer_DOWNLOAD FileTransfer_Dir = 1
)

// Enum value maps for FileTransfer_Dir.
var (
	FileTransfer_Dir_name = map[int32]string{
		0: "UPLOAD",
		1: "DOWNLOAD",
	}
	FileTransfer_Dir_value = map[string]int32{
		"UPLOAD":   0,
		"DOWNLOAD": 1,
	}
)

func (x FileTransfer_Dir) Enum() *FileTransfer_Dir {
	p := new(FileTransfer_Dir)
	*p = x
	return p
}

func (x FileTransfer_Dir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransfer_Dir) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_commands_proto_enumTypes[0].Descriptor()
}

func (FileTransfer_Dir) Type() protoreflect.EnumType {
	return &file_fleet_v1_commands_proto_enumTypes[0]
}

func (x FileTransfer_Dir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransfer_Dir.Descriptor instead.
func (FileTransfer_Dir) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4, 0}
}

type AgentUpdateResult_Status int32

const (
	AgentUpdateResult_STATUS_UNSPECIFIED  AgentUpdateResult_Status = 0
	AgentUpdateResult_SUCCESS             AgentUpdateResult_Status = 1
	AgentUpdateResult_SIG_INVALID         AgentUpdateResult_Status = 2
	AgentUpdateResult_SHA_MISMATCH        AgentUpdateResult_Status = 3
	AgentUpdateResult_DOWNLOAD_FAILED     AgentUpdateResult_Status = 4
	AgentUpdateResult_SWAP_FAILED         AgentUpdateResult_Status = 5
	AgentUpdateResult_HEALTH_CHECK_FAILED AgentUpdateResult_Status = 6
	AgentUpdateResult_ROLLED_BACK         AgentUpdateResult_Status = 7
)

// Enum value maps for AgentUpdateResult_Status.
var (
	AgentUpdateResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "SIG_INVALID",
		3: "SHA_MISMATCH",
		4: "DOWNLOAD_FAILED",
		5: "SWAP_FAILED",
		6: "HEALTH_CHECK_FAILED",
		7: "ROLLED_BACK",
	}
	AgentUpdateResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"SUCCESS":             1,
		"SIG_INVALID":         2,
		"SHA_MISMATCH":        3,
		"DOWNLOAD_FAILED":     4,
		"SWAP_FAILED":         5,
		"HEALTH_CHECK_FAILED": 6,
		"ROLLED_BACK":         7,
	}
)

func (x AgentUpdateResult_Status) Enum() *AgentUpdateResult_Status {
	p := new(AgentUpdateResult_Status)
	*p = x
	return p
}

func (x AgentUpdateResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentUpdateResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_commands_proto_enumTypes[1].Descriptor()
}

func (AgentUpdateResult_Status) Type() protoreflect.EnumType {
	return &file_fleet_v1_commands_proto_enumTypes[1]
}

func (x AgentUpdateResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentUpdateResult_Status.Descriptor instead.
func (AgentUpdateResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{9, 0}
}

type PkgUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []string               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgUpdate) Reset() {
	*x = PkgUpdate{}
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgUpdate) ProtoMessage() {}

func (x *PkgUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgUpdate.ProtoReflect.Descriptor instead.
func (*PkgUpdate) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *PkgUpdate) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *PkgUpdate) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type Reboot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reboot) Reset() {
	*x = Reboot{}
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reboot) ProtoMessage() {}

func (x *Reboot) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reboot.ProtoReflect.Descriptor instead.
func (*Reboot) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *Reboot) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *Reboot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShellExec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShellExec) Reset() {
	*x = ShellExec{}
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExec) ProtoMessage() {}

func (x *ShellExec) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExec.ProtoReflect.Descriptor instead.
func (*ShellExec) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ShellExec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ShellExec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellExec) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TerminalOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpen) Reset() {
	*x = TerminalOpen{}
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpen) ProtoMessage() {}

func (x *TerminalOpen) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpen.ProtoReflect.Descriptor instead.
func (*TerminalOpen) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           FileTransfer_Dir       `protobuf:"varint,1,opt,name=dir,proto3,enum=fleet.v1.FileTransfer_Dir" json:"dir,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *FileTransfer) GetDir() FileTransfer_Dir {
	if x != nil {
		return x.Dir
	}
	return FileTransfer_UPLOAD
}

func (x *FileTransfer) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileTransfer) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type DockerOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerOp) Reset() {
	*x = DockerOp{}
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerOp) ProtoMessage() {}

func (x *DockerOp) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerOp.ProtoReflect.Descriptor instead.
func (*DockerOp) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DockerOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DockerOp) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type GetFacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacts) Reset() {
	*x = GetFacts{}
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacts) ProtoMessage() {}

func (x *GetFacts) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacts.ProtoReflect.Descriptor instead.
func (*GetFacts) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *GetFacts) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PluginInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInvoke) Reset() {
	*x = PluginInvoke{}
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInvoke) ProtoMessage() {}

func (x *PluginInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInvoke.ProtoReflect.Descriptor instead.
func (*PluginInvoke) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInvoke) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInvoke) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AgentUpdateCmd struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId      string                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ManifestJson   []byte                 `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	ManifestSig    []byte                 `protobuf:"bytes,3,opt,name=manifest_sig,json=manifestSig,proto3" json:"manifest_sig,omitempty"`
	BinaryUrl      string                 `protobuf:"bytes,4,opt,name=binary_url,json=binaryUrl,proto3" json:"binary_url,omitempty"`
	DownloadToken  string                 `protobuf:"bytes,5,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	ExpectedSha256 string                 `protobuf:"bytes,6,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	ExpectedSize   uint64                 `protobuf:"varint,7,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	Force          bool                   `protobuf:"varint,8,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentUpdateCmd) Reset() {
	*x = AgentUpdateCmd{}
	mi := &file_fleet_v1_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateCmd) ProtoMessage() {}

func (x *AgentUpdateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateCmd.ProtoReflect.Descriptor instead.
func (*AgentUpdateCmd) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *AgentUpdateCmd) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *AgentUpdateCmd) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *AgentUpdateCmd) GetManifestSig() []byte {
	if x != nil {
		return x.ManifestSig
	}
	return nil
}

func (x *AgentUpdateCmd) GetBinaryUrl() string {
	if x != nil {
		return x.BinaryUrl
	}
	return ""
}

func (x *AgentUpdateCmd) GetDownloadToken() string {
	if x != nil {
		return x.DownloadToken
	}
	return ""
}

func (x *AgentUpdateCmd) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

func (x *AgentUpdateCmd) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

func (x *AgentUpdateCmd) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AgentUpdateResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	FromVersion   string                   `protobuf:"bytes,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion     string                   `protobuf:"bytes,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Status        AgentUpdateResult_Status `protobuf:"varint,3,opt,name=status,proto3,enum=fleet.v1.AgentUpdateResult_Status" json:"status,omitempty"`
	Error         string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpdateResult) Reset() {
	*x = AgentUpdateResult{}
	mi := &file_fleet_v1_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateResult) ProtoMessage() {}

func (x *AgentUpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateResult.ProtoReflect.Descriptor instead.
func (*AgentUpdateResult) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *AgentUpdateResult) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *AgentUpdateResult) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *AgentUpdateResult) GetStatus() AgentUpdateResult_Status {
	if x != nil {
		return x.Status
	}
	return AgentUpdateResult_STATUS_UNSPECIFIED
}

func (x *AgentUpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_fleet_v1_commands_proto protoreflect.FileDescriptor

const file_fleet_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x17fleet/v1/commands.proto\x12\bfleet.v1\">\n" +
	"\tPkgUpdate\x12\x18\n" +
	"\aclasses\x18\x01 \x03(\tR\aclasses\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"E\n" +
	"\x06Reboot\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"b\n" +
	"\tShellExec\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"U\n" +
	"\fTerminalOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"\x9d\x01\n" +
	"\fFileTransfer\x12,\n" +
	"\x03dir\x18\x01 \x01(\x0e2\x1a.fleet.v1.FileTransfer.DirR\x03dir\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"\x1f\n" +
	"\x03Dir\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x00\x12\f\n" +
	"\bDOWNLOAD\x10\x01\"8\n" +
	"\bDockerOp\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\"\x1e\n" +
	"\bGetFacts\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"E\n" +
	"\fPluginInvoke\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xa1\x02\n" +
	"\x0eAgentUpdateCmd\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\tR\treleaseId\x12#\n" +
	"\rmanifest_json\x18\x02 \x01(\fR\fmanifestJson\x12!\n" +
	"\fmanifest_sig\x18\x03 \x01(\fR\vmanifestSig\x12\x1d\n" +
	"\n" +
	"binary_url\x18\x04 \x01(\tR\tbinaryUrl\x12%\n" +
	"\x0edownload_token\x18\x05 \x01(\tR\rdownloadToken\x12'\n" +
	"\x0fexpected_sha256\x18\x06 \x01(\tR\x0eexpectedSha256\x12#\n" +
	"\rexpected_size\x18\a \x01(\x04R\fexpectedSize\x12\x14\n" +
	"\x05force\x18\b \x01(\bR\x05force\"\xca\x02\n" +
	"\x11AgentUpdateResult\x12!\n" +
	"\ffrom_version\x18\x01 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\tR\ttoVersion\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".fleet.v1.AgentUpdateResult.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa0\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x0f\n" +
	"\vSIG_INVALID\x10\x02\x12\x10\n" +
	"\fSHA_MISMATCH\x10\x03\x12\x13\n" +
	"\x0fDOWNLOAD_FAILED\x10\x04\x12\x0f\n" +
	"\vSWAP_FAILED\x10\x05\x12\x17\n" +
	"\x13HEALTH_CHECK_FAILED\x10\x06\x12\x0f\n" +
	"\vROLLED_BACK\x10\aB-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3"

var (
	file_fleet_v1_commands_proto_rawDescOnce sync.Once
	file_fleet_v1_commands_proto_rawDescData []byte
)

func file_fleet_v1_commands_proto_rawDescGZIP() []byte {
	file_fleet_v1_commands_proto_rawDescOnce.Do(func() {
		file_fleet_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_commands_proto_rawDesc), len(file_fleet_v1_commands_proto_rawDesc)))
	})
	return file_fleet_v1_commands_proto_rawDescData
}

var file_fleet_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fleet_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fleet_v1_commands_proto_goTypes = []any{
	(FileTransfer_Dir)(0),         // 0: fleet.v1.FileTransfer.Dir
	(AgentUpdateResult_Status)(0), // 1: fleet.v1.AgentUpdateResult.Status
	(*PkgUpdate)(nil),             // 2: fleet.v1.PkgUpdate
	(*Reboot)(nil),                // 3: fleet.v1.Reboot
	(*ShellExec)(nil),             // 4: fleet.v1.ShellExec
	(*TerminalOpen)(nil),          // 5: fleet.v1.TerminalOpen
	(*FileTransfer)(nil),          // 6: fleet.v1.FileTransfer
	(*DockerOp)(nil),              // 7: fleet.v1.DockerOp
	(*GetFacts)(nil),              // 8: fleet.v1.GetFacts
	(*PluginInvoke)(nil),          // 9: fleet.v1.PluginInvoke
	(*AgentUpdateCmd)(nil),        // 10: fleet.v1.AgentUpdateCmd
	(*AgentUpdateResult)(nil),     // 11: fleet.v1.AgentUpdateResult
}
var file_fleet_v1_commands_proto_depIdxs = []int32{
	0, // 0: fleet.v1.FileTransfer.dir:type_name -> fleet.v1.FileTransfer.Dir
	1, // 1: fleet.v1.AgentUpdateResult.status:type_name -> fleet.v1.AgentUpdateResult.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleet_v1_commands_proto_init() }
func file_fleet_v1_commands_proto_init() {
	if File_fleet_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_commands_proto_rawDesc), len(file_fleet_v1_commands_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1_commands_proto_goTypes,
		DependencyIndexes: file_fleet_v1_commands_proto_depIdxs,
		EnumInfos:         file_fleet_v1_commands_proto_enumTypes,
		MessageInfos:      file_fleet_v1_commands_proto_msgTypes,
	}.Build()
	File_fleet_v1_commands_proto = out.File
	file_fleet_v1_commands_proto_goTypes = nil
	file_fleet_v1_commands_proto_depIdxs = nil
}
