// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: fleet/v1/commands.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransfer_Dir int32

const (
	FileTransfer_UPLOAD   FileTransfer_Dir = 0
	FileTransfer_DOWNLOAD FileTransfer_Dir = 1
)

// Enum value maps for FileTransfer_Dir.
var (
	FileTransfer_Dir_name = map[int32]string{
		0: "UPLOAD",
		1: "DOWNLOAD",
	}
	FileTransfer_Dir_value = map[string]int32{
		"UPLOAD":   0,
		"DOWNLOAD": 1,
	}
)

func (x FileTransfer_Dir) Enum() *FileTransfer_Dir {
	p := new(FileTransfer_Dir)
	*p = x
	return p
}

func (x FileTransfer_Dir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransfer_Dir) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_commands_proto_enumTypes[0].Descriptor()
}

func (FileTransfer_Dir) Type() protoreflect.EnumType {
	return &file_fleet_v1_commands_proto_enumTypes[0]
}

func (x FileTransfer_Dir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransfer_Dir.Descriptor instead.
func (FileTransfer_Dir) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4, 0}
}

type PkgUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []string               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgUpdate) Reset() {
	*x = PkgUpdate{}
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgUpdate) ProtoMessage() {}

func (x *PkgUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgUpdate.ProtoReflect.Descriptor instead.
func (*PkgUpdate) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *PkgUpdate) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *PkgUpdate) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type Reboot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reboot) Reset() {
	*x = Reboot{}
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reboot) ProtoMessage() {}

func (x *Reboot) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reboot.ProtoReflect.Descriptor instead.
func (*Reboot) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *Reboot) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *Reboot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShellExec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShellExec) Reset() {
	*x = ShellExec{}
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExec) ProtoMessage() {}

func (x *ShellExec) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExec.ProtoReflect.Descriptor instead.
func (*ShellExec) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ShellExec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ShellExec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellExec) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TerminalOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpen) Reset() {
	*x = TerminalOpen{}
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpen) ProtoMessage() {}

func (x *TerminalOpen) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpen.ProtoReflect.Descriptor instead.
func (*TerminalOpen) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           FileTransfer_Dir       `protobuf:"varint,1,opt,name=dir,proto3,enum=fleet.v1.FileTransfer_Dir" json:"dir,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *FileTransfer) GetDir() FileTransfer_Dir {
	if x != nil {
		return x.Dir
	}
	return FileTransfer_UPLOAD
}

func (x *FileTransfer) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileTransfer) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type DockerOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerOp) Reset() {
	*x = DockerOp{}
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerOp) ProtoMessage() {}

func (x *DockerOp) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerOp.ProtoReflect.Descriptor instead.
func (*DockerOp) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DockerOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DockerOp) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type GetFacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacts) Reset() {
	*x = GetFacts{}
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacts) ProtoMessage() {}

func (x *GetFacts) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacts.ProtoReflect.Descriptor instead.
func (*GetFacts) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *GetFacts) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PluginInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInvoke) Reset() {
	*x = PluginInvoke{}
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInvoke) ProtoMessage() {}

func (x *PluginInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInvoke.ProtoReflect.Descriptor instead.
func (*PluginInvoke) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInvoke) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInvoke) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_fleet_v1_commands_proto protoreflect.FileDescriptor

const file_fleet_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x17fleet/v1/commands.proto\x12\bfleet.v1\">\n" +
	"\tPkgUpdate\x12\x18\n" +
	"\aclasses\x18\x01 \x03(\tR\aclasses\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"E\n" +
	"\x06Reboot\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"b\n" +
	"\tShellExec\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"U\n" +
	"\fTerminalOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"\x9d\x01\n" +
	"\fFileTransfer\x12,\n" +
	"\x03dir\x18\x01 \x01(\x0e2\x1a.fleet.v1.FileTransfer.DirR\x03dir\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"\x1f\n" +
	"\x03Dir\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x00\x12\f\n" +
	"\bDOWNLOAD\x10\x01\"8\n" +
	"\bDockerOp\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\"\x1e\n" +
	"\bGetFacts\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"E\n" +
	"\fPluginInvoke\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadb\x06proto3"

var (
	file_fleet_v1_commands_proto_rawDescOnce sync.Once
	file_fleet_v1_commands_proto_rawDescData []byte
)

func file_fleet_v1_commands_proto_rawDescGZIP() []byte {
	file_fleet_v1_commands_proto_rawDescOnce.Do(func() {
		file_fleet_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_commands_proto_rawDesc), len(file_fleet_v1_commands_proto_rawDesc)))
	})
	return file_fleet_v1_commands_proto_rawDescData
}

var file_fleet_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fleet_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fleet_v1_commands_proto_goTypes = []any{
	(FileTransfer_Dir)(0), // 0: fleet.v1.FileTransfer.Dir
	(*PkgUpdate)(nil),     // 1: fleet.v1.PkgUpdate
	(*Reboot)(nil),        // 2: fleet.v1.Reboot
	(*ShellExec)(nil),     // 3: fleet.v1.ShellExec
	(*TerminalOpen)(nil),  // 4: fleet.v1.TerminalOpen
	(*FileTransfer)(nil),  // 5: fleet.v1.FileTransfer
	(*DockerOp)(nil),      // 6: fleet.v1.DockerOp
	(*GetFacts)(nil),      // 7: fleet.v1.GetFacts
	(*PluginInvoke)(nil),  // 8: fleet.v1.PluginInvoke
}
var file_fleet_v1_commands_proto_depIdxs = []int32{
	0, // 0: fleet.v1.FileTransfer.dir:type_name -> fleet.v1.FileTransfer.Dir
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fleet_v1_commands_proto_init() }
func file_fleet_v1_commands_proto_init() {
	if File_fleet_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_commands_proto_rawDesc), len(file_fleet_v1_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1_commands_proto_goTypes,
		DependencyIndexes: file_fleet_v1_commands_proto_depIdxs,
		EnumInfos:         file_fleet_v1_commands_proto_enumTypes,
		MessageInfos:      file_fleet_v1_commands_proto_msgTypes,
	}.Build()
	File_fleet_v1_commands_proto = out.File
	file_fleet_v1_commands_proto_goTypes = nil
	file_fleet_v1_commands_proto_depIdxs = nil
}
