// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: fleet/v1/commands.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransfer_Dir int32

const (
	FileTransfer_UPLOAD   FileTransfer_Dir = 0
	FileTransfer_DOWNLOAD FileTransfer_Dir = 1
)

// Enum value maps for FileTransfer_Dir.
var (
	FileTransfer_Dir_name = map[int32]string{
		0: "UPLOAD",
		1: "DOWNLOAD",
	}
	FileTransfer_Dir_value = map[string]int32{
		"UPLOAD":   0,
		"DOWNLOAD": 1,
	}
)

func (x FileTransfer_Dir) Enum() *FileTransfer_Dir {
	p := new(FileTransfer_Dir)
	*p = x
	return p
}

func (x FileTransfer_Dir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransfer_Dir) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_commands_proto_enumTypes[0].Descriptor()
}

func (FileTransfer_Dir) Type() protoreflect.EnumType {
	return &file_fleet_v1_commands_proto_enumTypes[0]
}

func (x FileTransfer_Dir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransfer_Dir.Descriptor instead.
func (FileTransfer_Dir) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4, 0}
}

type AgentUpdateResult_Status int32

const (
	AgentUpdateResult_STATUS_UNSPECIFIED  AgentUpdateResult_Status = 0
	AgentUpdateResult_SUCCESS             AgentUpdateResult_Status = 1
	AgentUpdateResult_SIG_INVALID         AgentUpdateResult_Status = 2
	AgentUpdateResult_SHA_MISMATCH        AgentUpdateResult_Status = 3
	AgentUpdateResult_DOWNLOAD_FAILED     AgentUpdateResult_Status = 4
	AgentUpdateResult_SWAP_FAILED         AgentUpdateResult_Status = 5
	AgentUpdateResult_HEALTH_CHECK_FAILED AgentUpdateResult_Status = 6
	AgentUpdateResult_ROLLED_BACK         AgentUpdateResult_Status = 7
)

// Enum value maps for AgentUpdateResult_Status.
var (
	AgentUpdateResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "SIG_INVALID",
		3: "SHA_MISMATCH",
		4: "DOWNLOAD_FAILED",
		5: "SWAP_FAILED",
		6: "HEALTH_CHECK_FAILED",
		7: "ROLLED_BACK",
	}
	AgentUpdateResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"SUCCESS":             1,
		"SIG_INVALID":         2,
		"SHA_MISMATCH":        3,
		"DOWNLOAD_FAILED":     4,
		"SWAP_FAILED":         5,
		"HEALTH_CHECK_FAILED": 6,
		"ROLLED_BACK":         7,
	}
)

func (x AgentUpdateResult_Status) Enum() *AgentUpdateResult_Status {
	p := new(AgentUpdateResult_Status)
	*p = x
	return p
}

func (x AgentUpdateResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentUpdateResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_commands_proto_enumTypes[1].Descriptor()
}

func (AgentUpdateResult_Status) Type() protoreflect.EnumType {
	return &file_fleet_v1_commands_proto_enumTypes[1]
}

func (x AgentUpdateResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentUpdateResult_Status.Descriptor instead.
func (AgentUpdateResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{9, 0}
}

type PkgUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classes []string `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	DryRun  bool     `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
}

func (x *PkgUpdate) Reset() {
	*x = PkgUpdate{}
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgUpdate) ProtoMessage() {}

func (x *PkgUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgUpdate.ProtoReflect.Descriptor instead.
func (*PkgUpdate) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *PkgUpdate) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *PkgUpdate) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type Reboot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DelaySeconds uint32 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason       string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Reboot) Reset() {
	*x = Reboot{}
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reboot) ProtoMessage() {}

func (x *Reboot) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reboot.ProtoReflect.Descriptor instead.
func (*Reboot) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *Reboot) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *Reboot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShellExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command        string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSeconds uint32   `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *ShellExec) Reset() {
	*x = ShellExec{}
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExec) ProtoMessage() {}

func (x *ShellExec) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExec.ProtoReflect.Descriptor instead.
func (*ShellExec) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ShellExec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ShellExec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellExec) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TerminalOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols      uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows      uint32 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *TerminalOpen) Reset() {
	*x = TerminalOpen{}
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpen) ProtoMessage() {}

func (x *TerminalOpen) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpen.ProtoReflect.Descriptor instead.
func (*TerminalOpen) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type FileTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir        FileTransfer_Dir `protobuf:"varint,1,opt,name=dir,proto3,enum=fleet.v1.FileTransfer_Dir" json:"dir,omitempty"`
	RemotePath string           `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	SizeBytes  uint64           `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *FileTransfer) GetDir() FileTransfer_Dir {
	if x != nil {
		return x.Dir
	}
	return FileTransfer_UPLOAD
}

func (x *FileTransfer) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileTransfer) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type DockerOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op        string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Container string `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *DockerOp) Reset() {
	*x = DockerOp{}
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerOp) ProtoMessage() {}

func (x *DockerOp) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerOp.ProtoReflect.Descriptor instead.
func (*DockerOp) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DockerOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DockerOp) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type GetFacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetFacts) Reset() {
	*x = GetFacts{}
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacts) ProtoMessage() {}

func (x *GetFacts) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacts.ProtoReflect.Descriptor instead.
func (*GetFacts) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *GetFacts) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PluginInvoke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PluginInvoke) Reset() {
	*x = PluginInvoke{}
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInvoke) ProtoMessage() {}

func (x *PluginInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInvoke.ProtoReflect.Descriptor instead.
func (*PluginInvoke) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInvoke) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInvoke) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AgentUpdateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseId      string `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ManifestJson   []byte `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	ManifestSig    []byte `protobuf:"bytes,3,opt,name=manifest_sig,json=manifestSig,proto3" json:"manifest_sig,omitempty"`
	BinaryUrl      string `protobuf:"bytes,4,opt,name=binary_url,json=binaryUrl,proto3" json:"binary_url,omitempty"`
	DownloadToken  string `protobuf:"bytes,5,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	ExpectedSha256 string `protobuf:"bytes,6,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	ExpectedSize   uint64 `protobuf:"varint,7,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	Force          bool   `protobuf:"varint,8,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *AgentUpdateCmd) Reset() {
	*x = AgentUpdateCmd{}
	mi := &file_fleet_v1_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateCmd) ProtoMessage() {}

func (x *AgentUpdateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateCmd.ProtoReflect.Descriptor instead.
func (*AgentUpdateCmd) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *AgentUpdateCmd) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *AgentUpdateCmd) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *AgentUpdateCmd) GetManifestSig() []byte {
	if x != nil {
		return x.ManifestSig
	}
	return nil
}

func (x *AgentUpdateCmd) GetBinaryUrl() string {
	if x != nil {
		return x.BinaryUrl
	}
	return ""
}

func (x *AgentUpdateCmd) GetDownloadToken() string {
	if x != nil {
		return x.DownloadToken
	}
	return ""
}

func (x *AgentUpdateCmd) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

func (x *AgentUpdateCmd) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

func (x *AgentUpdateCmd) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AgentUpdateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromVersion string                   `protobuf:"bytes,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion   string                   `protobuf:"bytes,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Status      AgentUpdateResult_Status `protobuf:"varint,3,opt,name=status,proto3,enum=fleet.v1.AgentUpdateResult_Status" json:"status,omitempty"`
	Error       string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AgentUpdateResult) Reset() {
	*x = AgentUpdateResult{}
	mi := &file_fleet_v1_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateResult) ProtoMessage() {}

func (x *AgentUpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateResult.ProtoReflect.Descriptor instead.
func (*AgentUpdateResult) Descriptor() ([]byte, []int) {
	return file_fleet_v1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *AgentUpdateResult) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *AgentUpdateResult) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *AgentUpdateResult) GetStatus() AgentUpdateResult_Status {
	if x != nil {
		return x.Status
	}
	return AgentUpdateResult_STATUS_UNSPECIFIED
}

func (x *AgentUpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_fleet_v1_commands_proto protoreflect.FileDescriptor

var file_fleet_v1_commands_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x2e, 0x76, 0x31, 0x22, 0x3e, 0x0a, 0x09, 0x50, 0x6b, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72,
	0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79,
	0x52, 0x75, 0x6e, 0x22, 0x45, 0x0a, 0x06, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x62, 0x0a, 0x09, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x55,
	0x0a, 0x0c, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x52,
	0x03, 0x64, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x50, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x10, 0x01, 0x22, 0x38, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4f,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22,
	0x1e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x46, 0x61, 0x63, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x45, 0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa1, 0x02, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x53, 0x69, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x12,
	0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0xca, 0x02, 0x0a, 0x11, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0xa0, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x49, 0x47, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x48, 0x41, 0x5f, 0x4d, 0x49, 0x53,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x57, 0x41, 0x50, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x12, 0x17, 0x0a,
	0x13, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x44,
	0x5f, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x07, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6c, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x68,
	0x6c, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fleet_v1_commands_proto_rawDescOnce sync.Once
	file_fleet_v1_commands_proto_rawDescData = file_fleet_v1_commands_proto_rawDesc
)

func file_fleet_v1_commands_proto_rawDescGZIP() []byte {
	file_fleet_v1_commands_proto_rawDescOnce.Do(func() {
		file_fleet_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_fleet_v1_commands_proto_rawDescData)
	})
	return file_fleet_v1_commands_proto_rawDescData
}

var file_fleet_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fleet_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fleet_v1_commands_proto_goTypes = []any{
	(FileTransfer_Dir)(0),         // 0: fleet.v1.FileTransfer.Dir
	(AgentUpdateResult_Status)(0), // 1: fleet.v1.AgentUpdateResult.Status
	(*PkgUpdate)(nil),             // 2: fleet.v1.PkgUpdate
	(*Reboot)(nil),                // 3: fleet.v1.Reboot
	(*ShellExec)(nil),             // 4: fleet.v1.ShellExec
	(*TerminalOpen)(nil),          // 5: fleet.v1.TerminalOpen
	(*FileTransfer)(nil),          // 6: fleet.v1.FileTransfer
	(*DockerOp)(nil),              // 7: fleet.v1.DockerOp
	(*GetFacts)(nil),              // 8: fleet.v1.GetFacts
	(*PluginInvoke)(nil),          // 9: fleet.v1.PluginInvoke
	(*AgentUpdateCmd)(nil),        // 10: fleet.v1.AgentUpdateCmd
	(*AgentUpdateResult)(nil),     // 11: fleet.v1.AgentUpdateResult
}
var file_fleet_v1_commands_proto_depIdxs = []int32{
	0, // 0: fleet.v1.FileTransfer.dir:type_name -> fleet.v1.FileTransfer.Dir
	1, // 1: fleet.v1.AgentUpdateResult.status:type_name -> fleet.v1.AgentUpdateResult.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleet_v1_commands_proto_init() }
func file_fleet_v1_commands_proto_init() {
	if File_fleet_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fleet_v1_commands_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1_commands_proto_goTypes,
		DependencyIndexes: file_fleet_v1_commands_proto_depIdxs,
		EnumInfos:         file_fleet_v1_commands_proto_enumTypes,
		MessageInfos:      file_fleet_v1_commands_proto_msgTypes,
	}.Build()
	File_fleet_v1_commands_proto = out.File
	file_fleet_v1_commands_proto_rawDesc = nil
	file_fleet_v1_commands_proto_goTypes = nil
	file_fleet_v1_commands_proto_depIdxs = nil
}
