// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet/v1/envelope.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_LOW  RiskLevel = 0
	RiskLevel_RISK_MED  RiskLevel = 1
	RiskLevel_RISK_HIGH RiskLevel = 2
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LOW",
		1: "RISK_MED",
		2: "RISK_HIGH",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LOW":  0,
		"RISK_MED":  1,
		"RISK_HIGH": 2,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_fleet_v1_envelope_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_envelope_proto_rawDescGZIP(), []int{0}
}

type CapabilityToken struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Biscuit        []byte                 `protobuf:"bytes,1,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	DeclaredScopes []string               `protobuf:"bytes,2,rep,name=declared_scopes,json=declaredScopes,proto3" json:"declared_scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilityToken) Reset() {
	*x = CapabilityToken{}
	mi := &file_fleet_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityToken) ProtoMessage() {}

func (x *CapabilityToken) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityToken.ProtoReflect.Descriptor instead.
func (*CapabilityToken) Descriptor() ([]byte, []int) {
	return file_fleet_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityToken) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

func (x *CapabilityToken) GetDeclaredScopes() []string {
	if x != nil {
		return x.DeclaredScopes
	}
	return nil
}

type CommandEnvelope struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CommandId  string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	HostId     string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Sequence   uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Nonce      []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	IssuedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuedBy   string                 `protobuf:"bytes,7,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	Risk       RiskLevel              `protobuf:"varint,8,opt,name=risk,proto3,enum=fleet.v1.RiskLevel" json:"risk,omitempty"`
	Capability *CapabilityToken       `protobuf:"bytes,9,opt,name=capability,proto3" json:"capability,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandEnvelope_PkgUpdate
	//	*CommandEnvelope_Reboot
	//	*CommandEnvelope_ShellExec
	//	*CommandEnvelope_TerminalOpen
	//	*CommandEnvelope_FileTransfer
	//	*CommandEnvelope_DockerOp
	//	*CommandEnvelope_GetFacts
	//	*CommandEnvelope_PluginInvoke
	Payload       isCommandEnvelope_Payload `protobuf_oneof:"payload"`
	Signature     []byte                    `protobuf:"bytes,200,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_fleet_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_fleet_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *CommandEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandEnvelope) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommandEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CommandEnvelope) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CommandEnvelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CommandEnvelope) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

func (x *CommandEnvelope) GetRisk() RiskLevel {
	if x != nil {
		return x.Risk
	}
	return RiskLevel_RISK_LOW
}

func (x *CommandEnvelope) GetCapability() *CapabilityToken {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *CommandEnvelope) GetPayload() isCommandEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandEnvelope) GetPkgUpdate() *PkgUpdate {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_PkgUpdate); ok {
			return x.PkgUpdate
		}
	}
	return nil
}

func (x *CommandEnvelope) GetReboot() *Reboot {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *CommandEnvelope) GetShellExec() *ShellExec {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_ShellExec); ok {
			return x.ShellExec
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalOpen() *TerminalOpen {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_TerminalOpen); ok {
			return x.TerminalOpen
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileTransfer() *FileTransfer {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_FileTransfer); ok {
			return x.FileTransfer
		}
	}
	return nil
}

func (x *CommandEnvelope) GetDockerOp() *DockerOp {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_DockerOp); ok {
			return x.DockerOp
		}
	}
	return nil
}

func (x *CommandEnvelope) GetGetFacts() *GetFacts {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_GetFacts); ok {
			return x.GetFacts
		}
	}
	return nil
}

func (x *CommandEnvelope) GetPluginInvoke() *PluginInvoke {
	if x != nil {
		if x, ok := x.Payload.(*CommandEnvelope_PluginInvoke); ok {
			return x.PluginInvoke
		}
	}
	return nil
}

func (x *CommandEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isCommandEnvelope_Payload interface {
	isCommandEnvelope_Payload()
}

type CommandEnvelope_PkgUpdate struct {
	PkgUpdate *PkgUpdate `protobuf:"bytes,100,opt,name=pkg_update,json=pkgUpdate,proto3,oneof"`
}

type CommandEnvelope_Reboot struct {
	Reboot *Reboot `protobuf:"bytes,101,opt,name=reboot,proto3,oneof"`
}

type CommandEnvelope_ShellExec struct {
	ShellExec *ShellExec `protobuf:"bytes,102,opt,name=shell_exec,json=shellExec,proto3,oneof"`
}

type CommandEnvelope_TerminalOpen struct {
	TerminalOpen *TerminalOpen `protobuf:"bytes,103,opt,name=terminal_open,json=terminalOpen,proto3,oneof"`
}

type CommandEnvelope_FileTransfer struct {
	FileTransfer *FileTransfer `protobuf:"bytes,104,opt,name=file_transfer,json=fileTransfer,proto3,oneof"`
}

type CommandEnvelope_DockerOp struct {
	DockerOp *DockerOp `protobuf:"bytes,105,opt,name=docker_op,json=dockerOp,proto3,oneof"`
}

type CommandEnvelope_GetFacts struct {
	GetFacts *GetFacts `protobuf:"bytes,106,opt,name=get_facts,json=getFacts,proto3,oneof"`
}

type CommandEnvelope_PluginInvoke struct {
	PluginInvoke *PluginInvoke `protobuf:"bytes,107,opt,name=plugin_invoke,json=pluginInvoke,proto3,oneof"`
}

func (*CommandEnvelope_PkgUpdate) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_Reboot) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_ShellExec) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_TerminalOpen) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_FileTransfer) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_DockerOp) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_GetFacts) isCommandEnvelope_Payload() {}

func (*CommandEnvelope_PluginInvoke) isCommandEnvelope_Payload() {}

var File_fleet_v1_envelope_proto protoreflect.FileDescriptor

const file_fleet_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x17fleet/v1/envelope.proto\x12\bfleet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17fleet/v1/commands.proto\"T\n" +
	"\x0fCapabilityToken\x12\x18\n" +
	"\abiscuit\x18\x01 \x01(\fR\abiscuit\x12'\n" +
	"\x0fdeclared_scopes\x18\x02 \x03(\tR\x0edeclaredScopes\"\xd5\x06\n" +
	"\x0fCommandEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tissued_by\x18\a \x01(\tR\bissuedBy\x12'\n" +
	"\x04risk\x18\b \x01(\x0e2\x13.fleet.v1.RiskLevelR\x04risk\x129\n" +
	"\n" +
	"capability\x18\t \x01(\v2\x19.fleet.v1.CapabilityTokenR\n" +
	"capability\x124\n" +
	"\n" +
	"pkg_update\x18d \x01(\v2\x13.fleet.v1.PkgUpdateH\x00R\tpkgUpdate\x12*\n" +
	"\x06reboot\x18e \x01(\v2\x10.fleet.v1.RebootH\x00R\x06reboot\x124\n" +
	"\n" +
	"shell_exec\x18f \x01(\v2\x13.fleet.v1.ShellExecH\x00R\tshellExec\x12=\n" +
	"\rterminal_open\x18g \x01(\v2\x16.fleet.v1.TerminalOpenH\x00R\fterminalOpen\x12=\n" +
	"\rfile_transfer\x18h \x01(\v2\x16.fleet.v1.FileTransferH\x00R\ffileTransfer\x121\n" +
	"\tdocker_op\x18i \x01(\v2\x12.fleet.v1.DockerOpH\x00R\bdockerOp\x121\n" +
	"\tget_facts\x18j \x01(\v2\x12.fleet.v1.GetFactsH\x00R\bgetFacts\x12=\n" +
	"\rplugin_invoke\x18k \x01(\v2\x16.fleet.v1.PluginInvokeH\x00R\fpluginInvoke\x12\x1d\n" +
	"\tsignature\x18\xc8\x01 \x01(\fR\tsignatureB\t\n" +
	"\apayload*6\n" +
	"\tRiskLevel\x12\f\n" +
	"\bRISK_LOW\x10\x00\x12\f\n" +
	"\bRISK_MED\x10\x01\x12\r\n" +
	"\tRISK_HIGH\x10\x02B-Z+github.com/hlhelper/hl-agent/proto/fleet/v1b\x06proto3"

var (
	file_fleet_v1_envelope_proto_rawDescOnce sync.Once
	file_fleet_v1_envelope_proto_rawDescData []byte
)

func file_fleet_v1_envelope_proto_rawDescGZIP() []byte {
	file_fleet_v1_envelope_proto_rawDescOnce.Do(func() {
		file_fleet_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_envelope_proto_rawDesc), len(file_fleet_v1_envelope_proto_rawDesc)))
	})
	return file_fleet_v1_envelope_proto_rawDescData
}

var file_fleet_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fleet_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fleet_v1_envelope_proto_goTypes = []any{
	(RiskLevel)(0),                // 0: fleet.v1.RiskLevel
	(*CapabilityToken)(nil),       // 1: fleet.v1.CapabilityToken
	(*CommandEnvelope)(nil),       // 2: fleet.v1.CommandEnvelope
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*PkgUpdate)(nil),             // 4: fleet.v1.PkgUpdate
	(*Reboot)(nil),                // 5: fleet.v1.Reboot
	(*ShellExec)(nil),             // 6: fleet.v1.ShellExec
	(*TerminalOpen)(nil),          // 7: fleet.v1.TerminalOpen
	(*FileTransfer)(nil),          // 8: fleet.v1.FileTransfer
	(*DockerOp)(nil),              // 9: fleet.v1.DockerOp
	(*GetFacts)(nil),              // 10: fleet.v1.GetFacts
	(*PluginInvoke)(nil),          // 11: fleet.v1.PluginInvoke
}
var file_fleet_v1_envelope_proto_depIdxs = []int32{
	3,  // 0: fleet.v1.CommandEnvelope.issued_at:type_name -> google.protobuf.Timestamp
	3,  // 1: fleet.v1.CommandEnvelope.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: fleet.v1.CommandEnvelope.risk:type_name -> fleet.v1.RiskLevel
	1,  // 3: fleet.v1.CommandEnvelope.capability:type_name -> fleet.v1.CapabilityToken
	4,  // 4: fleet.v1.CommandEnvelope.pkg_update:type_name -> fleet.v1.PkgUpdate
	5,  // 5: fleet.v1.CommandEnvelope.reboot:type_name -> fleet.v1.Reboot
	6,  // 6: fleet.v1.CommandEnvelope.shell_exec:type_name -> fleet.v1.ShellExec
	7,  // 7: fleet.v1.CommandEnvelope.terminal_open:type_name -> fleet.v1.TerminalOpen
	8,  // 8: fleet.v1.CommandEnvelope.file_transfer:type_name -> fleet.v1.FileTransfer
	9,  // 9: fleet.v1.CommandEnvelope.docker_op:type_name -> fleet.v1.DockerOp
	10, // 10: fleet.v1.CommandEnvelope.get_facts:type_name -> fleet.v1.GetFacts
	11, // 11: fleet.v1.CommandEnvelope.plugin_invoke:type_name -> fleet.v1.PluginInvoke
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fleet_v1_envelope_proto_init() }
func file_fleet_v1_envelope_proto_init() {
	if File_fleet_v1_envelope_proto != nil {
		return
	}
	file_fleet_v1_commands_proto_init()
	file_fleet_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*CommandEnvelope_PkgUpdate)(nil),
		(*CommandEnvelope_Reboot)(nil),
		(*CommandEnvelope_ShellExec)(nil),
		(*CommandEnvelope_TerminalOpen)(nil),
		(*CommandEnvelope_FileTransfer)(nil),
		(*CommandEnvelope_DockerOp)(nil),
		(*CommandEnvelope_GetFacts)(nil),
		(*CommandEnvelope_PluginInvoke)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_envelope_proto_rawDesc), len(file_fleet_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1_envelope_proto_goTypes,
		DependencyIndexes: file_fleet_v1_envelope_proto_depIdxs,
		EnumInfos:         file_fleet_v1_envelope_proto_enumTypes,
		MessageInfos:      file_fleet_v1_envelope_proto_msgTypes,
	}.Build()
	File_fleet_v1_envelope_proto = out.File
	file_fleet_v1_envelope_proto_goTypes = nil
	file_fleet_v1_envelope_proto_depIdxs = nil
}
