// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fleet/v1/reenroll.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReEnroll_Challenge_FullMethodName = "/fleet.v1.ReEnroll/Challenge"
	ReEnroll_Complete_FullMethodName  = "/fleet.v1.ReEnroll/Complete"
)

// ReEnrollClient is the client API for ReEnroll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReEnroll is dialed TLS-only (no client cert). Auth is via Ed25519 challenge
// signed with the host's durable signing key.
type ReEnrollClient interface {
	Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CertIssueResponse, error)
}

type reEnrollClient struct {
	cc grpc.ClientConnInterface
}

func NewReEnrollClient(cc grpc.ClientConnInterface) ReEnrollClient {
	return &reEnrollClient{cc}
}

func (c *reEnrollClient) Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, ReEnroll_Challenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reEnrollClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CertIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertIssueResponse)
	err := c.cc.Invoke(ctx, ReEnroll_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReEnrollServer is the server API for ReEnroll service.
// All implementations must embed UnimplementedReEnrollServer
// for forward compatibility.
//
// ReEnroll is dialed TLS-only (no client cert). Auth is via Ed25519 challenge
// signed with the host's durable signing key.
type ReEnrollServer interface {
	Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	Complete(context.Context, *CompleteRequest) (*CertIssueResponse, error)
	mustEmbedUnimplementedReEnrollServer()
}

// UnimplementedReEnrollServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReEnrollServer struct{}

func (UnimplementedReEnrollServer) Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Challenge not implemented")
}
func (UnimplementedReEnrollServer) Complete(context.Context, *CompleteRequest) (*CertIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedReEnrollServer) mustEmbedUnimplementedReEnrollServer() {}
func (UnimplementedReEnrollServer) testEmbeddedByValue()                  {}

// UnsafeReEnrollServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReEnrollServer will
// result in compilation errors.
type UnsafeReEnrollServer interface {
	mustEmbedUnimplementedReEnrollServer()
}

func RegisterReEnrollServer(s grpc.ServiceRegistrar, srv ReEnrollServer) {
	// If the following call pancis, it indicates UnimplementedReEnrollServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReEnroll_ServiceDesc, srv)
}

func _ReEnroll_Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReEnrollServer).Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReEnroll_Challenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReEnrollServer).Challenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReEnroll_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReEnrollServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReEnroll_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReEnrollServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReEnroll_ServiceDesc is the grpc.ServiceDesc for ReEnroll service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReEnroll_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.ReEnroll",
	HandlerType: (*ReEnrollServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Challenge",
			Handler:    _ReEnroll_Challenge_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _ReEnroll_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleet/v1/reenroll.proto",
}
