// Package pb provides minimal proto bindings for testing.
// This is a shim; real bindings will be generated by protoc.
package pb

import (
	"time"
)

// RiskLevel enum
type RiskLevel int32

const (
	RISK_LOW  RiskLevel = 0
	RISK_MED  RiskLevel = 1
	RISK_HIGH RiskLevel = 2
)

// CapabilityToken holds biscuit capability.
type CapabilityToken struct {
	Biscuit         []byte
	DeclaredScopes  []string
}

// CommandEnvelope wraps a command with metadata, nonce, sequence, signature.
type CommandEnvelope struct {
	CommandID   string
	HostID      string
	Sequence    uint64
	Nonce       []byte
	IssuedAt    *time.Time
	ExpiresAt   *time.Time
	IssuedBy    string
	Risk        RiskLevel
	Capability  *CapabilityToken
	Signature   []byte

	// Payload field discriminator (oneof emulation)
	PkgUpdate    *PkgUpdate
	Reboot       *Reboot
	ShellExec    *ShellExec
	TerminalOpen *TerminalOpen
	FileTransfer *FileTransfer
	DockerOp     *DockerOp
	GetFacts     *GetFacts
	PluginInvoke *PluginInvoke
}

// Command types
type PkgUpdate struct {
	Classes []string
	DryRun  bool
}

type Reboot struct {
	DelaySeconds uint32
	Reason       string
}

type ShellExec struct {
	Command        string
	Args           []string
	TimeoutSeconds uint32
}

type TerminalOpen struct {
	SessionID string
	Cols      uint32
	Rows      uint32
}

type FileTransfer struct {
	Dir        int32 // 0=UPLOAD, 1=DOWNLOAD
	RemotePath string
	SizeBytes  uint64
}

type DockerOp struct {
	Op        string
	Container string
}

type GetFacts struct {
	Keys []string
}

type PluginInvoke struct {
	PluginID string
	Payload  []byte
}

// WhichPayload returns the name of the set payload field.
func (e *CommandEnvelope) WhichPayload() string {
	if e.PkgUpdate != nil {
		return "pkg_update"
	}
	if e.Reboot != nil {
		return "reboot"
	}
	if e.ShellExec != nil {
		return "shell_exec"
	}
	if e.TerminalOpen != nil {
		return "terminal_open"
	}
	if e.FileTransfer != nil {
		return "file_transfer"
	}
	if e.DockerOp != nil {
		return "docker_op"
	}
	if e.GetFacts != nil {
		return "get_facts"
	}
	if e.PluginInvoke != nil {
		return "plugin_invoke"
	}
	return ""
}
